AVLTree< T > Class Template Reference
AVLTree< T > Class Template Reference
#include <AVLTree.h>
Public Member Functions
AVLTree (ObjectAllocator *OA=0, bool ShareOA=false)
virtual ~AVLTree ()
virtual void insert (const T &value)
virtual void remove (const T &value)
AVLTree (ObjectAllocator *OA=0, bool ShareOA=false)
virtual ~AVLTree ()
virtual void insert (const T &value) throw (BSTException)
virtual void remove (const T &value)
Static Public Member Functions
static bool ImplementedBalanceFactor (void)
static bool ImplementedBalanceFactor (void)
Private Member Functions
void insert_node_avl (typename BSTree< T >::BinTree &tree, const T &value)
void insert_node_avl_helper (typename BSTree< T >::BinTree &tree, const T &value, std::stack< typename BSTree< T >::BinTree * > &nodes)
void remove_node_avl (typename BSTree< T >::BinTree &tree, const T &value)
void remove_node_avl_helper (typename BSTree< T >::BinTree &tree, const T &value, std::stack< typename BSTree< T >::BinTree * > &nodes)
void balance_tree (std::stack< typename BSTree< T >::BinTree * > &nodes)
void rotate_right (typename BSTree< T >::BinTree &tree)
void rotate_left (typename BSTree< T >::BinTree &tree)
void insert_node_avl (typename BSTree< T >::BinTree &tree, const T &value)
void insert_node_avl_helper (typename BSTree< T >::BinTree &tree, const T &value, std::stack< typename BSTree< T >::BinTree * > &nodes)
void remove_node_avl (typename BSTree< T >::BinTree &tree, const T &value)
void remove_node_avl_helper (typename BSTree< T >::BinTree &tree, const T &value, std::stack< typename BSTree< T >::BinTree * > &nodes)
void balance_tree (std::stack< typename BSTree< T >::BinTree * > &nodes)
void rotate_right (typename BSTree< T >::BinTree &tree)
void rotate_left (typename BSTree< T >::BinTree &tree)
Detailed Description
template<typename T>
class AVLTree< T >
Definition at line 25 of file AVLTree.h.
Constructor & Destructor Documentation
template<typename T > AVLTree< T >::AVLTree (ObjectAllocator * OA = 0, bool ShareOA = false)
Constructor for a AVLTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
OA The allocator to use for all of the AVLTree's allocations.
ShareOA If the BSTree object must create its own allocator.
Definition at line 34 of file AVLTree.cpp.
template<typename T > AVLTree< T >::~AVLTree () [virtual]
Destructor for an AVLTree.
Author:
louis.coyleii
Date:
10/21/14
Definition at line 48 of file AVLTree.cpp.
template<typename T> AVLTree< T >::AVLTree (ObjectAllocator * OA = 0, bool ShareOA = false)
template<typename T> virtual AVLTree< T >::~AVLTree () [virtual]
Member Function Documentation
template<typename T > void AVLTree< T >::balance_tree (std::stack< typename BSTree< T >::BinTree * > & nodes) [private]
To balance the AVLTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
nodes A stack of nodes that were visited.
Definition at line 245 of file AVLTree.cpp.
References BSTree< T >::BinTreeNode::left, BSTree< T >::BinTreeNode::right, and BSTree< T >::tree_height().
template<typename T> void AVLTree< T >::balance_tree (std::stack< typename BSTree< T >::BinTree * > & nodes) [private]
template<typename T > bool AVLTree< T >::ImplementedBalanceFactor (void) [static]
Returns true if efficiency implemented.
Author:
louis.coyleii
Date:
10/21/14
Returns:
bool Whether or not efficiency was implemented.
Definition at line 96 of file AVLTree.cpp.
Referenced by AVLStress().
template<typename T> static bool AVLTree< T >::ImplementedBalanceFactor (void) [static]
template<typename T> virtual void AVLTree< T >::insert (const T & value) throw (BSTException) [virtual]
To insert a node into the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
value The value to be inserted.
Reimplemented from BSTree< T >.
template<typename T > void AVLTree< T >::insert (const T & value) [virtual]
To insert a node into the AVLTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
value The value to be inserted.
Reimplemented from BSTree< T >.
Definition at line 64 of file AVLTree.cpp.
Referenced by AVLStress().
template<typename T > void AVLTree< T >::insert_node_avl (typename BSTree< T >::BinTree & tree, const T & value) [private]
To insert a node into the AVLTree, calls helper inserter.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree The root of the tree to insert into.
value The value to be inserted into the tree.
Definition at line 113 of file AVLTree.cpp.
template<typename T> void AVLTree< T >::insert_node_avl (typename BSTree< T >::BinTree & tree, const T & value) [private]
template<typename T > void AVLTree< T >::insert_node_avl_helper (typename BSTree< T >::BinTree & tree, const T & value, std::stack< typename BSTree< T >::BinTree * > & nodes) [private]
To insert a node into the AVLTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree Initially the root of the tree to insert into.
value The value to insert into the tree.
nodes A stack of visited nodes.
Definition at line 132 of file AVLTree.cpp.
References BSTree< T >::BinTreeNode::count, BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T> void AVLTree< T >::insert_node_avl_helper (typename BSTree< T >::BinTree & tree, const T & value, std::stack< typename BSTree< T >::BinTree * > & nodes) [private]
template<typename T > void AVLTree< T >::remove (const T & value) [virtual]
To remove a node from the AVLTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
value The value to be removed.
Reimplemented from BSTree< T >.
Definition at line 80 of file AVLTree.cpp.
Referenced by AVLStress().
template<typename T> virtual void AVLTree< T >::remove (const T & value) [virtual]
To remove a node from the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
value The value to be removed.
Reimplemented from BSTree< T >.
template<typename T> void AVLTree< T >::remove_node_avl (typename BSTree< T >::BinTree & tree, const T & value) [private]
template<typename T > void AVLTree< T >::remove_node_avl (typename BSTree< T >::BinTree & tree, const T & value) [private]
Recursive helper to remove a node from the AVLTree
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree The root of the tree to remove from.
value The value to be removed from the tree.
Definition at line 169 of file AVLTree.cpp.
template<typename T> void AVLTree< T >::remove_node_avl_helper (typename BSTree< T >::BinTree & tree, const T & value, std::stack< typename BSTree< T >::BinTree * > & nodes) [private]
template<typename T > void AVLTree< T >::remove_node_avl_helper (typename BSTree< T >::BinTree & tree, const T & value, std::stack< typename BSTree< T >::BinTree * > & nodes) [private]
To help in removing a node recursively from the AVLTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree Initially the root of the tree to remove from.
value The value to be removed from the tree.
nodes A stack of visited nodes.
Definition at line 188 of file AVLTree.cpp.
References BSTree< T >::BinTreeNode::count, BSTree< T >::BinTreeNode::data, BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T> void AVLTree< T >::rotate_left (typename BSTree< T >::BinTree & tree) [private]
template<typename T > void AVLTree< T >::rotate_left (typename BSTree< T >::BinTree & tree) [private]
To rotate the AVLTree left.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree The node of the tree to rotate about
Definition at line 335 of file AVLTree.cpp.
References BSTree< T >::BinTreeNode::count, BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T > void AVLTree< T >::rotate_right (typename BSTree< T >::BinTree & tree) [private]
To rotate the AVLTree right.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree The node of the tree to rotate about.
Definition at line 304 of file AVLTree.cpp.
References BSTree< T >::BinTreeNode::count, BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T> void AVLTree< T >::rotate_right (typename BSTree< T >::BinTree & tree) [private]
The documentation for this class was generated from the following files:
AVLTree.h
AVLTreeold.h
AVLTree.cpp