BSTException Class Reference
BSTException Class Reference
#include <BSTree.h>
Public Types
enum BST_EXCEPTION { E_DUPLICATE, E_NO_MEMORY, E_DUPLICATE, E_NO_MEMORY }
enum BST_EXCEPTION { E_DUPLICATE, E_NO_MEMORY, E_DUPLICATE, E_NO_MEMORY }
Public Member Functions
BSTException (int ErrCode, const std::string &Message)
virtual int code (void) const
virtual const char * what (void) const throw ()
virtual ~BSTException ()
BSTException (int ErrCode, const std::string &Message)
virtual int code (void) const
virtual const char * what (void) const throw ()
virtual ~BSTException () throw ()
Private Attributes
int error_code_
std::string message_
Detailed Description
Definition at line 29 of file BSTree.h.
Member Enumeration Documentation
enum BSTException::BST_EXCEPTION
Enumerator:
E_DUPLICATE
E_NO_MEMORY
E_DUPLICATE
E_NO_MEMORY
Definition at line 43 of file BSTree.h.
enum BSTException::BST_EXCEPTION
Enumerator:
E_DUPLICATE
E_NO_MEMORY
E_DUPLICATE
E_NO_MEMORY
Definition at line 43 of file BSTreeold.h.
Constructor & Destructor Documentation
BSTException::BSTException (int ErrCode, const std::string & Message) [inline]
Definition at line 32 of file BSTree.h.
virtual BSTException::~BSTException () [inline, virtual]
Definition at line 42 of file BSTree.h.
BSTException::BSTException (int ErrCode, const std::string & Message) [inline]
Definition at line 32 of file BSTreeold.h.
virtual BSTException::~BSTException () throw () [inline, virtual]
Definition at line 42 of file BSTreeold.h.
Member Function Documentation
virtual int BSTException::code (void) const [inline, virtual]
Definition at line 36 of file BSTree.h.
References error_code_.
Referenced by Test1(), Test2(), Test3(), Test4(), Test5(), Test6(), Test7(), Test8(), TestIndex(), and TestStrings().
virtual int BSTException::code (void) const [inline, virtual]
Definition at line 36 of file BSTreeold.h.
References error_code_.
virtual const char* BSTException::what (void) const throw () [inline, virtual]
Definition at line 39 of file BSTreeold.h.
References message_.
virtual const char* BSTException::what (void) const throw () [inline, virtual]
Definition at line 39 of file BSTree.h.
References message_.
Referenced by AVLStress().
Member Data Documentation
int BSTException::error_code_ [private]
Definition at line 46 of file BSTree.h.
Referenced by code().
std::string BSTException::message_ [private]
Definition at line 47 of file BSTree.h.
Referenced by what().
The documentation for this class was generated from the following files:
BSTree.h
BSTreeold.h