BSTree< T > Class Template Reference
BSTree< T > Class Template Reference
#include <BSTree.h>
Classes
struct BinTreeNode
Public Types
typedef BinTreeNode * BinTree
typedef BinTreeNode * BinTree
Public Member Functions
BSTree (ObjectAllocator *OA=0, bool ShareOA=false)
BSTree (const BSTree &rhs)
virtual ~BSTree ()
BSTree & operator= (const BSTree &rhs)
const BinTreeNode * operator[] (int index) const
virtual void insert (const T &value)
virtual void remove (const T &value)
void clear (void)
bool find (const T &value, unsigned &compares) const
bool empty (void) const
unsigned int size (void) const
int height (void) const
BinTree root (void) const
BSTree (ObjectAllocator *OA=0, bool ShareOA=false)
BSTree (const BSTree &rhs)
virtual ~BSTree ()
BSTree & operator= (const BSTree &rhs)
const BinTreeNode * operator[] (int index) const
virtual void insert (const T &value) throw (BSTException)
virtual void remove (const T &value)
void clear (void)
bool find (const T &value, unsigned &compares) const
bool empty (void) const
unsigned int size (void) const
int height (void) const
BinTree root (void) const
Protected Member Functions
BinTree & get_root (void)
BinTree make_node (const T &value)
void free_node (BinTree node)
int tree_height (BinTree tree) const
void find_predecessor (BinTree tree, BinTree &predecessor) const
bool find_node (BinTree tree, const T &value, unsigned &compares) const
int max (const int first, const int second) const
BinTree & get_root (void)
BinTree make_node (const T &value)
void free_node (BinTree node)
int tree_height (BinTree tree) const
void find_predecessor (BinTree tree, BinTree &predecessor) const
bool find_node (BinTree tree, const T &value, unsigned &compares) const
int max (const int first, const int second) const
Protected Attributes
BinTree root_
unsigned int size_
ObjectAllocator * oa_
bool freeoa_
bool shareoa_
Private Member Functions
void delete_node (BinTree &tree, const T &value)
void insert_node (BinTree &tree, const T &value)
const BinTreeNode * find_index (BinTree tree, int index) const
void free_all_nodes (BinTree &tree)
void copy_tree (BinTree &copy, BinTree tree)
void delete_node (BinTree &tree, const T &value)
void insert_node (BinTree &tree, const T &value)
const BinTreeNode * find_index (BinTree tree, int index) const
void free_all_nodes (BinTree &tree)
void copy_tree (BinTree &copy, BinTree tree)
Detailed Description
template<typename T>
class BSTree< T >
Definition at line 51 of file BSTree.h.
Member Typedef Documentation
template<typename T> typedef BinTreeNode* BSTree< T >::BinTree
Definition at line 65 of file BSTree.h.
template<typename T> typedef BinTreeNode* BSTree< T >::BinTree
Definition at line 65 of file BSTreeold.h.
Constructor & Destructor Documentation
template<typename T > BSTree< T >::BSTree (ObjectAllocator * OA = 0, bool ShareOA = false)
Constructor for a BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
OA The allocator to use for all of the BSTree's allocations.
ShareOA If the BSTree object is to share an allocator.
Definition at line 34 of file BSTree.cpp.
template<typename T > BSTree< T >::BSTree (const BSTree< T > & rhs)
Copy constructor for a BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
rhs The BStree to copy construct from.
Definition at line 65 of file BSTree.cpp.
References BSTree< T >::oa_, BSTree< T >::root_, BSTree< T >::shareoa_, and BSTree< T >::size_.
template<typename T > BSTree< T >::~BSTree () [virtual]
Destructor for a BSTree.
Author:
louis.coyleii
Date:
10/21/14
Definition at line 96 of file BSTree.cpp.
template<typename T> BSTree< T >::BSTree (ObjectAllocator * OA = 0, bool ShareOA = false)
template<typename T> BSTree< T >::BSTree (const BSTree< T > & rhs)
template<typename T> virtual BSTree< T >::~BSTree () [virtual]
Member Function Documentation
template<typename T > void BSTree< T >::clear (void)
Clears all nodes from the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Definition at line 261 of file BSTree.cpp.
template<typename T> void BSTree< T >::clear (void)
template<typename T > void BSTree< T >::copy_tree (BinTree & copy, BinTree tree) [private]
Copies the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree The tree to copy to.
Definition at line 617 of file BSTree.cpp.
References BSTree< T >::BinTreeNode::count, BSTree< T >::BinTreeNode::data, BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T> void BSTree< T >::copy_tree (BinTree & copy, BinTree tree) [private]
template<typename T> void BSTree< T >::delete_node (BinTree & tree, const T & value) [private]
template<typename T> void BSTree< T >::delete_node (BinTree & tree, const T & value) [private]
Deletes the node with value from tree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree Pointer to root of tree to delete from.
value The value of node to be deleted.
Definition at line 513 of file BSTree.cpp.
References BSTree< T >::BinTreeNode::count, BSTree< T >::BinTreeNode::data, BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T > bool BSTree< T >::empty (void) const
Returns if the BSTree is empty.
Author:
louis.coyleii
Date:
10/21/14
Returns:
bool Whether or not the BSTree is empty.
Definition at line 320 of file BSTree.cpp.
template<typename T> bool BSTree< T >::empty (void) const
template<typename T> bool BSTree< T >::find (const T & value, unsigned & compares) const
Finds a node in the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
value The value to find in the BSTree.
compares Reference to the number of compares needed to find node.
Returns:
bool Whether or not the node was found.
Definition at line 304 of file BSTree.cpp.
template<typename T> bool BSTree< T >::find (const T & value, unsigned & compares) const
template<typename T> const BinTreeNode* BSTree< T >::find_index (BinTree tree, int index) const [private]
template<typename T > const BSTree< T >::BinTreeNode * BSTree< T >::find_index (BinTree tree, int index) const [private]
Helper function for subscript operator.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree Initially the root of the tree to search in.
index The index to find node for.
Returns:
BinTreeNode* The node at index.
Definition at line 189 of file BSTree.cpp.
References BSTree< T >::BinTreeNode::count, BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T> bool BSTree< T >::find_node (BinTree tree, const T & value, unsigned & compares) const [protected]
Finds the node with value.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree Pointer to the root of tree to find in.
value The data to search for.
compares Counter for the number of times fn is called.
Definition at line 488 of file BSTree.cpp.
References BSTree< T >::BinTreeNode::data, BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T> bool BSTree< T >::find_node (BinTree tree, const T & value, unsigned & compares) const [protected]
template<typename T> void BSTree< T >::find_predecessor (BinTree tree, BinTree & predecessor) const [protected]
template<typename T > void BSTree< T >::find_predecessor (BinTree tree, BinTree & predecessor) const [protected]
Finds the predecessor of the node.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree The node to get the predecessor of.
predecessor The predecessor of the supplied node.
Definition at line 468 of file BSTree.cpp.
References BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T > void BSTree< T >::free_all_nodes (BinTree & tree) [private]
Clears all nodes from the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree Initially the root of the tree to clear.
Definition at line 279 of file BSTree.cpp.
References BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T> void BSTree< T >::free_all_nodes (BinTree & tree) [private]
template<typename T> void BSTree< T >::free_node (BinTree node) [protected]
template<typename T > void BSTree< T >::free_node (BinTree node) [protected]
Destructor for a node.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
node The node to be freed.
Definition at line 428 of file BSTree.cpp.
template<typename T> BinTree& BSTree< T >::get_root (void) [protected]
template<typename T > BSTree< T >::BinTree & BSTree< T >::get_root (void) [protected]
Gettor for the root of a BSTree.
Author:
louis.coyleii
Date:
10/21/14
Returns:
BinTree& The root of the BSTree.
Definition at line 387 of file BSTree.cpp.
template<typename T > int BSTree< T >::height (void) const
Returns the height of the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Returns:
int The maximum depth of the BSTree.
Definition at line 355 of file BSTree.cpp.
Referenced by PrintBST().
template<typename T> int BSTree< T >::height (void) const
template<typename T> void BSTree< T >::insert (const T & value) [virtual]
To insert a node into the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
value The value to be inserted.
Reimplemented in AVLTree< T >, and AVLTree< T >.
Definition at line 231 of file BSTree.cpp.
template<typename T> virtual void BSTree< T >::insert (const T & value) throw (BSTException) [virtual]
Reimplemented in AVLTree< T >, and AVLTree< T >.
template<typename T> void BSTree< T >::insert_node (BinTree & tree, const T & value) [private]
template<typename T> void BSTree< T >::insert_node (BinTree & tree, const T & value) [private]
Inserts a node with value into tree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree Pointer to root of tree to insert into.
value The data for the node to be inserted.
Definition at line 564 of file BSTree.cpp.
References BSTree< T >::BinTreeNode::count, BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
template<typename T> BinTree BSTree< T >::make_node (const T & value) [protected]
template<typename T> BSTree< T >::BinTree BSTree< T >::make_node (const T & value) [protected]
Constructor for a node.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
value The value to create the node with.
Returns:
BinTree Pointer to the created node.
Definition at line 405 of file BSTree.cpp.
References BSTException::E_NO_MEMORY, and OAException::what().
template<typename T > int BSTree< T >::max (const int first, const int second) const [protected]
Determines which parameter is the max.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
first The first value to compare.
second The second value to compare.
Returns:
int The value of the max of the two inputs.
Definition at line 598 of file BSTree.cpp.
template<typename T> int BSTree< T >::max (const int first, const int second) const [protected]
template<typename T> BSTree& BSTree< T >::operator= (const BSTree< T > & rhs)
template<typename T > BSTree< T > & BSTree< T >::operator= (const BSTree< T > & rhs)
Assignment operator for a BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
rhs The BSTree to assign from.
Returns:
BSTree<T>& The new BSTree, assigned from the rhs.
Definition at line 119 of file BSTree.cpp.
References BSTree< T >::oa_, BSTree< T >::root_, BSTree< T >::shareoa_, and BSTree< T >::size_.
template<typename T> const BinTreeNode* BSTree< T >::operator[] (int index) const
template<typename T > const BSTree< T >::BinTreeNode * BSTree< T >::operator[] (int index) const
Subscript operator for a BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
index The index of the node to access.
Returns:
BinTree Pointer to the node at index.
Definition at line 163 of file BSTree.cpp.
template<typename T> void BSTree< T >::remove (const T & value) [virtual]
To remove a node from the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
value The value to be removed.
Reimplemented in AVLTree< T >, and AVLTree< T >.
Definition at line 247 of file BSTree.cpp.
template<typename T> virtual void BSTree< T >::remove (const T & value) [virtual]
Reimplemented in AVLTree< T >, and AVLTree< T >.
template<typename T > BSTree< T >::BinTree BSTree< T >::root (void) const
Returns the root of the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Returns:
BinTree Pointer to the root node of the BSTree.
Definition at line 371 of file BSTree.cpp.
Referenced by SetTreePositions().
template<typename T> BinTree BSTree< T >::root (void) const
template<typename T > unsigned int BSTree< T >::size (void) const
Returns the number of nodes in the BSTree.
Author:
louis.coyleii
Date:
10/21/14
Returns:
unsigned int The number of nodes in the BSTree.
Definition at line 339 of file BSTree.cpp.
Referenced by AVLStress().
template<typename T> unsigned int BSTree< T >::size (void) const
template<typename T> int BSTree< T >::tree_height (BinTree tree) const [protected]
template<typename T > int BSTree< T >::tree_height (BinTree tree) const [protected]
Gettor for the height of a BSTree.
Author:
louis.coyleii
Date:
10/21/14
Parameters:
tree The tree to get the height of.
Returns:
int The height of the BSTree.
Definition at line 448 of file BSTree.cpp.
References BSTree< T >::BinTreeNode::left, and BSTree< T >::BinTreeNode::right.
Referenced by AVLTree< T >::balance_tree().
Member Data Documentation
template<typename T> bool BSTree< T >::freeoa_ [protected]
Definition at line 86 of file BSTree.h.
template<typename T> ObjectAllocator * BSTree< T >::oa_ [protected]
Definition at line 85 of file BSTree.h.
Referenced by BSTree< T >::BSTree(), and BSTree< T >::operator=().
template<typename T> BinTree BSTree< T >::root_ [protected]
Definition at line 83 of file BSTree.h.
Referenced by BSTree< T >::BSTree(), and BSTree< T >::operator=().
template<typename T> bool BSTree< T >::shareoa_ [protected]
Definition at line 87 of file BSTree.h.
Referenced by BSTree< T >::BSTree(), and BSTree< T >::operator=().
template<typename T> unsigned int BSTree< T >::size_ [protected]
Definition at line 84 of file BSTree.h.
Referenced by BSTree< T >::BSTree(), and BSTree< T >::operator=().
The documentation for this class was generated from the following files:
BSTree.h
BSTreeold.h
BSTree.cpp