HashTableException Class Reference
HashTableException Class Reference
#include <ChHashTable.h>
Public Types
enum HASHTABLE_EXCEPTION { E_ITEM_NOT_FOUND, E_DUPLICATE, E_NO_MEMORY }
Public Member Functions
HashTableException (int ErrCode, const std::string &Message)
virtual ~HashTableException ()
virtual int code (void) const
virtual const char * what (void) const
Private Attributes
int error_code_
std::string message_
Detailed Description
Definition at line 34 of file ChHashTable.h.
Member Enumeration Documentation
enum HashTableException::HASHTABLE_EXCEPTION
Enumerator:
E_ITEM_NOT_FOUND
E_DUPLICATE
E_NO_MEMORY
Definition at line 54 of file ChHashTable.h.
Constructor & Destructor Documentation
HashTableException::HashTableException (int ErrCode, const std::string & Message) [inline]
Definition at line 41 of file ChHashTable.h.
virtual HashTableException::~HashTableException () [inline, virtual]
Definition at line 44 of file ChHashTable.h.
Member Function Documentation
virtual int HashTableException::code (void) const [inline, virtual]
Definition at line 47 of file ChHashTable.h.
References error_code_.
Referenced by Test1(), Test2(), Test3(), Test4(), Test5(), and Test6().
virtual const char* HashTableException::what (void) const [inline, virtual]
Definition at line 51 of file ChHashTable.h.
References message_.
Member Data Documentation
int HashTableException::error_code_ [private]
Definition at line 37 of file ChHashTable.h.
Referenced by code().
std::string HashTableException::message_ [private]
Definition at line 38 of file ChHashTable.h.
Referenced by what().
The documentation for this class was generated from the following file:
ChHashTable.h