ChHashTable< T > Class Template Reference
ChHashTable< T > Class Template Reference
#include <ChHashTable.h>
Classes
struct ChHTHeadNode
struct ChHTNode
struct HTConfig
Public Types
typedef void(* FREEPROC)(T)
Public Member Functions
ChHashTable (const HTConfig &Config, ObjectAllocator *allocator=0)
~ChHashTable ()
void insert (const char *Key, const T &Data)
void remove (const char *Key)
const T & find (const char *Key) const
void clear (void)
HTStats GetStats (void) const
const ChHTHeadNode * GetTable (void) const
Private Member Functions
void grow (void)
void push_front (const T &Data, const char *Key, ChHTHeadNode &list)
void remove_node (ChHTNode *&prev)
void pop_front (ChHTHeadNode &list)
Private Attributes
HTStats stats_
ChHTHeadNode * head_
HTConfig config_
ObjectAllocator * oa_
Detailed Description
template<typename T>
class ChHashTable< T >
Definition at line 71 of file ChHashTable.h.
Member Typedef Documentation
template<typename T> typedef void(* ChHashTable< T >::FREEPROC)(T)
Definition at line 75 of file ChHashTable.h.
Constructor & Destructor Documentation
template<typename T > ChHashTable< T >::ChHashTable (const HTConfig & Config, ObjectAllocator * allocator = 0)
Returns true if efficiency implemented.
Author:
louis.coyleii
Date:
3/11/2014
Parameters:
Config
allocator Allocator to use for the
Returns:
bool Whether or not efficiency was implemented.
Definition at line 36 of file ChHashTable.cpp.
References ChHashTable< T >::HTConfig::HashFunc_, HTStats::HashFunc_, ChHashTable< T >::head_, ChHashTable< T >::HTConfig::InitialTableSize_, ChHashTable< T >::stats_, and HTStats::TableSize_.
template<typename T > ChHashTable< T >::~ChHashTable ()
Destructor for a ChHashTable.
Author:
louis.coyleii
Date:
11/12/14
Definition at line 52 of file ChHashTable.cpp.
Member Function Documentation
template<typename T > void ChHashTable< T >::clear (void)
Removes all items from the table (Doesn't deallocate table).
Author:
louis.coyleii
Date:
11/12/14
Definition at line 164 of file ChHashTable.cpp.
Referenced by Test6().
template<typename T > const T & ChHashTable< T >::find (const char * Key) const
Find and return data by key (returns 0 if not found).
Author:
louis.coyleii
Date:
11/12/14
Parameters:
Key The key to find an item for.
Returns:
T& The item that was found by key.
Definition at line 139 of file ChHashTable.cpp.
References ChHashTable< T >::ChHTNode::Data, HashTableException::E_ITEM_NOT_FOUND, ChHashTable< T >::ChHTNode::Key, and ChHashTable< T >::ChHTNode::Next.
Referenced by Test4().
template<typename T > HTStats ChHashTable< T >::GetStats (void) const
Allow the client to peer into the data.
Author:
louis.coyleii
Date:
11/12/14
Returns:
HTStats The stats for the table.
Definition at line 188 of file ChHashTable.cpp.
Referenced by DumpStats(), DumpTable(), and Test3().
template<typename T > const ChHashTable< T >::ChHTHeadNode * ChHashTable< T >::GetTable (void) const
Returns the head of the table.
Author:
louis.coyleii
Date:
11/12/14
Returns:
ChHTHeadNode* The head of the table.
Definition at line 204 of file ChHashTable.cpp.
Referenced by DumpTable().
template<typename T > void ChHashTable< T >::grow (void) [private]
Grows the table.
Author:
louis.coyleii
Date:
11/12/14
Definition at line 220 of file ChHashTable.cpp.
References GetClosestPrime().
template<typename T > void ChHashTable< T >::insert (const char * Key, const T & Data)
Inserts a key/data pair into table. Throws an exception if unsuccessful.
Author:
louis.coyleii
Date:
11/12/14
Parameters:
Key The key part of the pair to be inserted into table.
Data The data part of the pair to be inserted into table.
Definition at line 70 of file ChHashTable.cpp.
Referenced by Test1(), Test2(), Test3(), Test4(), Test5(), Test6(), Test7(), and Test8().
template<typename T > void ChHashTable< T >::pop_front (ChHTHeadNode & list) [private]
Pops the front of the list.
Author:
louis.coyleii
Date:
11/12/14
Parameters:
list The head of the list pop.
Definition at line 305 of file ChHashTable.cpp.
References ChHashTable< T >::ChHTNode::Next, and ChHashTable< T >::ChHTHeadNode::Nodes.
template<typename T > void ChHashTable< T >::push_front (const T & Data, const char * Key, ChHTHeadNode & list) [private]
Pushes a node with Data to the front of the list.
Author:
louis.coyleii
Date:
11/12/14
Parameters:
Data The data to be pushed to the front.
Key The key to be pushed to the front.
list The head of the list to add to.
Definition at line 261 of file ChHashTable.cpp.
References HashTableException::E_DUPLICATE, HashTableException::E_NO_MEMORY, ChHashTable< T >::ChHTNode::Key, ChHashTable< T >::ChHTNode::Next, and ChHashTable< T >::ChHTHeadNode::Nodes.
template<typename T > void ChHashTable< T >::remove (const char * Key)
Delete an item by key. Throws an exception if the key doesn't exist. Compacts the table by moving key/data pairs, if necessary
Author:
louis.coyleii
Date:
11/12/14
Parameters:
Key The key of the item to remove.
Definition at line 100 of file ChHashTable.cpp.
References ChHashTable< T >::ChHTNode::Data, HashTableException::E_ITEM_NOT_FOUND, ChHashTable< T >::ChHTNode::Key, ChHashTable< T >::ChHTNode::Next, and ChHashTable< T >::ChHTHeadNode::Nodes.
Referenced by Test2().
template<typename T > void ChHashTable< T >::remove_node (ChHTNode *& prev) [private]
Removes a node from the list.
Author:
louis.coyleii
Date:
11/12/14
Parameters:
prev The node before the node to remove.
Definition at line 330 of file ChHashTable.cpp.
References ChHashTable< T >::ChHTNode::Next.
Member Data Documentation
template<typename T> HTConfig ChHashTable< T >::config_ [private]
Definition at line 140 of file ChHashTable.h.
template<typename T> ChHTHeadNode* ChHashTable< T >::head_ [private]
Definition at line 139 of file ChHashTable.h.
Referenced by ChHashTable< T >::ChHashTable().
template<typename T> ObjectAllocator* ChHashTable< T >::oa_ [private]
Definition at line 141 of file ChHashTable.h.
template<typename T> HTStats ChHashTable< T >::stats_ [mutable, private]
Definition at line 138 of file ChHashTable.h.
Referenced by ChHashTable< T >::ChHashTable().
The documentation for this class was generated from the following files:
ChHashTable.h
ChHashTable.cpp