BList< T, Size > Class Template Reference
BList< T, Size > Class Template Reference
#include <BList.h>
Classes
struct BNode
Public Member Functions
BList ()
BList (const BList &rhs)
~BList () NOEXCEPT(true)
BList & operator= (const BList &rhs) NOEXCEPT(false)
void push_back (const T &value) NOEXCEPT(false)
void push_front (const T &value) NOEXCEPT(false)
void insert (const T &value) NOEXCEPT(false)
void remove (int index) NOEXCEPT(false)
void remove_by_value (const T &value)
int find (const T &value) const
T & operator[] (int index) NOEXCEPT(false)
const T & operator[] (int index) const NOEXCEPT(false)
size_t size (void) const
void clear (void)
const BNode * GetHead () const
BListStats GetStats () const
BList ()
BList (const BList &rhs)
~BList ()
BList & operator= (const BList &rhs) throw (BListException)
void push_back (const T &value) throw (BListException)
void push_front (const T &value) throw (BListException)
void insert (const T &value) throw (BListException)
void remove (int index) throw (BListException)
void remove_by_value (const T &value)
int find (const T &value) const
T & operator[] (int index) throw (BListException)
const T & operator[] (int index) const throw (BListException)
unsigned size (void) const
void clear (void)
const BNode * GetHead () const
BListStats GetStats () const
Static Public Member Functions
static size_t nodesize (void)
static unsigned nodesize (void)
Private Member Functions
void pop_front (void)
bool empty (void)
BNode * new_node (const T &value)
void remove_node (BNode *todelete)
bool full (BNode *isfull)
void insert_after (BNode *insertafter, const T &value)
void split_node (BNode *tosplit, const T &value)
void insert_before (BNode *insertbefore, const T &value)
BNode * copy_node (BNode *tocopy)
void insert_into (BNode *insertinto, const T &value)
void pop_front (void)
bool empty (void)
BNode * new_node (const T &value)
void remove_node (BNode *todelete)
bool full (BNode *isfull)
void insert_after (BNode *insertafter, const T &value)
void split_node (BNode *tosplit, const T &value)
void insert_before (BNode *insertbefore, const T &value)
BNode * copy_node (BNode *tocopy)
void insert_into (BNode *insertinto, const T &value)
Private Attributes
BNode * head_
BNode * tail_
BListStats stats
Detailed Description
template<typename T, int Size = 1>
class BList< T, Size >
Definition at line 69 of file BList.h.
Constructor & Destructor Documentation
template<typename T , int Size> BList< T, Size >::BList ()
Default constructor.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Definition at line 34 of file BList.cpp.
template<typename T , int Size> BList< T, Size >::BList (const BList< T, Size > & rhs)
Copy Constructor.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Parameters:
rhs The right hand side.
Definition at line 60 of file BList.cpp.
References BListStats::ArraySize, BList< T, Size >::head_, BList< T, Size >::BNode::next, BListStats::NodeSize, BList< T, Size >::BNode::prev, and BList< T, Size >::stats.
template<typename T , int Size> BList< T, Size >::~BList ()
Destructor.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Definition at line 113 of file BList.cpp.
template<typename T, int Size = 1> BList< T, Size >::BList ()
template<typename T, int Size = 1> BList< T, Size >::BList (const BList< T, Size > & rhs)
template<typename T, int Size = 1> BList< T, Size >::~BList ()
Member Function Documentation
template<typename T , int Size> void BList< T, Size >::clear (void)
Delete all nodes.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter.
Size The number of array elements per node..
Definition at line 733 of file BList.cpp.
Referenced by test12_8().
template<typename T, int Size = 1> void BList< T, Size >::clear (void)
template<typename T , int Size> BList< T, Size >::BNode * BList< T, Size >::copy_node (BNode * tocopy) [private]
Creates a copy of tocopy.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node.
Parameters:
tocopy The node to be copied.
Returns:
BNode* The copied node.
Definition at line 1168 of file BList.cpp.
References BList< T, Size >::BNode::count, and BList< T, Size >::BNode::values.
template<typename T, int Size = 1> BNode* BList< T, Size >::copy_node (BNode * tocopy) [private]
template<typename T, int Size = 1> bool BList< T, Size >::empty (void) [private]
template<typename T , int Size> bool BList< T, Size >::empty (void) [private]
Returns whether or not the list is empty.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node.
Returns:
bool Whether or not the array is empty.
Definition at line 849 of file BList.cpp.
template<typename T , int Size> int BList< T, Size >::find (const T & value) const
Searches for the first match for the given constant.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Parameters:
value The value to search for.
Returns:
An int, being the index of the element containing value.
Definition at line 541 of file BList.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::BNode::next, and BList< T, Size >::BNode::values.
Referenced by test2(), test5_1(), test5_16(), test5_2(), test5_4(), test5_8(), test6_16(), test6_512(), and test6_64().
template<typename T, int Size = 1> int BList< T, Size >::find (const T & value) const
template<typename T , int Size> bool BList< T, Size >::full (BNode * isfull) [private]
Checks if the node's array is full.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node.
Parameters:
isfull The node to check fullness of.
Returns:
bool Whether or not the node is full.
Definition at line 952 of file BList.cpp.
References BList< T, Size >::BNode::count.
template<typename T, int Size = 1> bool BList< T, Size >::full (BNode * isfull) [private]
template<typename T, int Size = 1> const BNode* BList< T, Size >::GetHead () const
template<typename T , int Size> const BList< T, Size >::BNode * BList< T, Size >::GetHead () const
Gets the head node of the list.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node..
Returns:
BNode* Pointer to the head node of the list.
Definition at line 774 of file BList.cpp.
Referenced by DumpList(), and DumpListFlat().
template<typename T, int Size = 1> BListStats BList< T, Size >::GetStats () const
template<typename T , int Size> BListStats BList< T, Size >::GetStats () const
Returns the stats for the list.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node..
Returns:
BListStats The stats for the list.
Definition at line 794 of file BList.cpp.
Referenced by DumpStats().
template<typename T , int Size> void BList< T, Size >::insert (const T & value)
Inserts values into the list, arrays will be sorted.
Author:
Louis.coyleii
Date:
09/20/14
Exceptions:
BListException Thrown when a B List error condition occurs.
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Parameters:
value The value.
Definition at line 276 of file BList.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::BNode::next, and BList< T, Size >::BNode::values.
Referenced by test1(), test10_1(), test10_4(), test11_8(), test12_8(), test2(), test3_1(), test3_16(), test3_2(), test3_4(), test3_8(), test4_1(), test4_16(), test4_2(), test4_4(), test4_8(), test6_16(), test6_512(), test6_64(), test9_1(), test9_4(), testA(), testB(), testC(), testD(), and testE().
template<typename T, int Size = 1> void BList< T, Size >::insert (const T & value) throw (BListException)
template<typename T, int Size = 1> void BList< T, Size >::insert_after (BNode * insertafter, const T & value) [private]
template<typename T , int Size> void BList< T, Size >::insert_after (BNode * insertafter, const T & value) [private]
Inserts a value after insertafter.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node.
Parameters:
insertafter The node to insert a value after.
value The value to be inserted.
Definition at line 975 of file BList.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::BNode::next, BList< T, Size >::BNode::prev, and BList< T, Size >::BNode::values.
template<typename T , int Size> void BList< T, Size >::insert_before (BNode * insertbefore, const T & value) [private]
Inserts a value before insertbefore.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node.
Parameters:
insertbefore The node to insert a value before.
value The value to be inserted.
Definition at line 1111 of file BList.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::BNode::next, BList< T, Size >::BNode::prev, and BList< T, Size >::BNode::values.
template<typename T, int Size = 1> void BList< T, Size >::insert_before (BNode * insertbefore, const T & value) [private]
template<typename T , int Size> void BList< T, Size >::insert_into (BNode * insertinto, const T & value) [private]
Inserts a value into insertinto.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node.
Parameters:
insertinto The node to insert a value into.
value The value to be inserted.
Definition at line 1199 of file BList.cpp.
References BList< T, Size >::BNode::count, and BList< T, Size >::BNode::values.
template<typename T, int Size = 1> void BList< T, Size >::insert_into (BNode * insertinto, const T & value) [private]
template<typename T , int Size> BList< T, Size >::BNode * BList< T, Size >::new_node (const T & value) [private]
Returns a new node with specified value.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node.
Returns:
BNode* The new node with specified value.
Definition at line 872 of file BList.cpp.
References BList< T, Size >::BNode::count, BListException::E_NO_MEMORY, and BList< T, Size >::BNode::values.
template<typename T, int Size = 1> BNode* BList< T, Size >::new_node (const T & value) [private]
template<typename T, int Size = 1> static unsigned BList< T, Size >::nodesize (void) [static]
template<typename T , int Size> size_t BList< T, Size >::nodesize (void) [static]
Gets the nodesize.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter.
Size The number of array elements per node..
Returns:
An unsigned, being size of the node.
Definition at line 754 of file BList.cpp.
Referenced by test1(), test10_1(), test10_4(), test11_8(), test12_8(), test1_1(), test1_16(), test1_2(), test1_4(), test1_8(), test2(), test2_1(), test2_16(), test2_2(), test2_4(), test2_8(), test3_1(), test3_16(), test3_2(), test3_4(), test3_8(), test4_1(), test4_16(), test4_2(), test4_4(), test4_8(), test5_1(), test5_16(), test5_2(), test5_4(), test5_8(), test6_16(), test6_512(), test6_64(), test7_1(), test7_2(), test7_4(), test7_8(), test8_1(), test8_2(), test8_4(), test8_8(), test9_1(), test9_4(), testA(), testB(), testC(), and testD().
template<typename T , int Size> BList< T, Size > & BList< T, Size >::operator= (const BList< T, Size > & rhs)
Assignment operator.
Author:
Louis.coyleii
Date:
09/20/14
Exceptions:
BListException Thrown when a B List error condition occurs.
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Parameters:
rhs The right hand side.
Returns:
The result of the operation.
Definition at line 136 of file BList.cpp.
References BList< T, Size >::BNode::next, and BList< T, Size >::BNode::prev.
template<typename T, int Size = 1> BList& BList< T, Size >::operator= (const BList< T, Size > & rhs) throw (BListException)
template<typename T, int Size = 1> T& BList< T, Size >::operator[] (int index) throw (BListException)
template<typename T, int Size = 1> const T& BList< T, Size >::operator[] (int index) const throw (BListException)
template<typename T , int Size> T & BList< T, Size >::operator[] (int index)
Subscript operator for l-values.
Author:
Louis.coyleii
Date:
09/20/14
Exceptions:
BListException Thrown when a B List error condition occurs.
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Parameters:
index Zero-based index of the.
Returns:
The value of the element at the index.
Definition at line 585 of file BList.cpp.
References BList< T, Size >::BNode::count, BListException::E_BAD_INDEX, BList< T, Size >::BNode::next, and BList< T, Size >::BNode::values.
template<typename T , int Size> const T & BList< T, Size >::operator[] (int index) const
Subscript operator for r-values.
Author:
Louis.coyleii
Date:
09/20/14
Exceptions:
BListException Thrown when a B List error condition occurs.
Template Parameters:
T Generic type parameter.
Size The number of array elements per node..
Parameters:
index Zero-based index of the.
Returns:
The value of the element at the index.
Definition at line 652 of file BList.cpp.
References BList< T, Size >::BNode::count, BListException::E_BAD_INDEX, BList< T, Size >::BNode::next, and BList< T, Size >::BNode::values.
template<typename T, int Size = 1> void BList< T, Size >::pop_front (void) [private]
template<typename T , int Size> void BList< T, Size >::pop_front (void) [private]
Pops the front of the list.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node..
Definition at line 812 of file BList.cpp.
References BList< T, Size >::BNode::count, and BList< T, Size >::BNode::next.
template<typename T , int Size> void BList< T, Size >::push_back (const T & value)
Pushes value onto back of the list, arrays will be unsorted.
Author:
Louis.coyleii
Date:
09/20/14
Exceptions:
BListException Thrown when a B List error condition occurs.
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Parameters:
value The value.
Definition at line 198 of file BList.cpp.
Referenced by test2_1(), test2_16(), test2_2(), test2_4(), test2_8(), test5_1(), test5_16(), test5_2(), test5_4(), test5_8(), test7_1(), test7_2(), test7_4(), test7_8(), test8_1(), test8_2(), test8_4(), and test8_8().
template<typename T, int Size = 1> void BList< T, Size >::push_back (const T & value) throw (BListException)
template<typename T, int Size = 1> void BList< T, Size >::push_front (const T & value) throw (BListException)
template<typename T , int Size> void BList< T, Size >::push_front (const T & value)
Pushes value onto front of the list, arrays will be unsorted.
Author:
Louis.coyleii
Date:
09/20/14
Exceptions:
BListException Thrown when a B List error condition occurs.
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Parameters:
value The value.
Definition at line 237 of file BList.cpp.
Referenced by test1_1(), test1_16(), test1_2(), test1_4(), and test1_8().
template<typename T, int Size = 1> void BList< T, Size >::remove (int index) throw (BListException)
template<typename T , int Size> void BList< T, Size >::remove (int index)
Removes the element by the given index.
Author:
Louis.coyleii
Date:
09/20/14
Exceptions:
BListException Thrown when a B List error condition occurs.
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Parameters:
index Zero-based index of the list.
Definition at line 414 of file BList.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::BNode::next, BList< T, Size >::BNode::prev, and BList< T, Size >::BNode::values.
Referenced by test2(), test7_1(), test7_2(), test7_4(), test7_8(), and testA().
template<typename T , int Size> void BList< T, Size >::remove_by_value (const T & value)
Removes the element by the given value.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter.
Size The number of array elements per node.
Parameters:
value The value to remove.
Definition at line 478 of file BList.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::BNode::next, BList< T, Size >::BNode::prev, and BList< T, Size >::BNode::values.
Referenced by test2(), test8_1(), test8_2(), test8_4(), and test8_8().
template<typename T, int Size = 1> void BList< T, Size >::remove_by_value (const T & value)
template<typename T, int Size = 1> void BList< T, Size >::remove_node (BNode * todelete) [private]
template<typename T , int Size> void BList< T, Size >::remove_node (BNode * todelete) [private]
Removes the node that is pointed to by todelete.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node.
Parameters:
todelete The node to be removed from the list.
Definition at line 912 of file BList.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::BNode::next, and BList< T, Size >::BNode::prev.
template<typename T , int Size> size_t BList< T, Size >::size (void) const
Total number of items (not nodes).
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter.
Size The number of array elements per node..
Returns:
An unsigned, being the size of the list.
Definition at line 716 of file BList.cpp.
Referenced by print_subscript().
template<typename T, int Size = 1> unsigned BList< T, Size >::size (void) const
template<typename T , int Size> void BList< T, Size >::split_node (BNode * tosplit, const T & value) [private]
Splits a node, placing half of the elements into each of the new nodes.
Author:
Louis.coyleii
Date:
09/20/14
Template Parameters:
T Generic type parameter, data stored in node.
Size The number of array elements per node.
Parameters:
tosplit The node to split.
value The value to add to one of the new nodes.
Returns:
BNode* Pointer to the first of the two new nodes.
Definition at line 1029 of file BList.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::BNode::next, BList< T, Size >::BNode::prev, and BList< T, Size >::BNode::values.
template<typename T, int Size = 1> void BList< T, Size >::split_node (BNode * tosplit, const T & value) [private]
Member Data Documentation
template<typename T, int Size = 1> BNode * BList< T, Size >::head_ [private]
Definition at line 113 of file BList.h.
Referenced by BList< T, Size >::BList().
template<typename T, int Size = 1> BListStats BList< T, Size >::stats [private]
Definition at line 115 of file BList.h.
Referenced by BList< T, Size >::BList().
template<typename T, int Size = 1> BNode * BList< T, Size >::tail_ [private]
Definition at line 114 of file BList.h.
The documentation for this class was generated from the following files:
BList.h
BListold.h
BList.cpp