driver.cpp File Reference
driver.cpp File Reference
#include <iostream>
#include <iomanip>
#include "BList.h"
#include "PRNG.h"
#include <algorithm>
Classes
struct Foo
Functions
int RandomInt (int low, int high)
template<typename T >
void SwapT (T &a, T &b)
template<typename T >
void Shuffle (T *array, int count)
template<typename T , int Size>
void DumpStats (const BList< T, Size > &blist)
template<typename T , int Size>
void DumpList (const BList< T, Size > &blist, bool flat=false)
template<typename T , int Size>
void DumpListFlat (const BList< T, Size > &blist)
void test1_1 ()
void test1_2 ()
void test1_4 ()
void test1_8 ()
void test1_16 ()
void test2_1 ()
void test2_2 ()
void test2_4 ()
void test2_8 ()
void test2_16 ()
void test3_1 ()
void test3_2 ()
void test3_4 ()
void test3_8 ()
void test3_16 ()
template<typename T , int Size>
void print_subscript (const BList< T, Size > &list)
void test4_1 ()
void test4_2 ()
void test4_4 ()
void test4_8 ()
void test4_16 ()
void test5_1 ()
void test5_2 ()
void test5_4 ()
void test5_8 ()
void test5_16 ()
void test6_16 ()
void test6_64 ()
void test6_512 ()
void test7_1 ()
void test7_2 ()
void test7_4 ()
void test7_8 ()
void test8_1 ()
void test8_2 ()
void test8_4 ()
void test8_8 ()
void test9_1 ()
void test9_4 ()
void test10_1 ()
void test10_4 ()
void test11_8 ()
void test12_8 ()
void test1 ()
std::ostream & operator<< (std::ostream &os, const Foo &rhs)
void test2 ()
void testA ()
void testB ()
void testC ()
void testD ()
void testE ()
int main (int argc, char **argv)
Function Documentation
template<typename T , int Size> void DumpList (const BList< T, Size > & blist, bool flat = false)
Definition at line 57 of file driver.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::GetHead(), BList< T, Size >::BNode::next, and BList< T, Size >::BNode::values.
Referenced by test1(), test10_1(), test10_4(), test11_8(), test12_8(), test1_1(), test1_16(), test1_2(), test1_4(), test1_8(), test2(), test2_1(), test2_16(), test2_2(), test2_4(), test2_8(), test3_1(), test3_16(), test3_2(), test3_4(), test3_8(), test4_1(), test4_16(), test4_2(), test4_4(), test4_8(), test5_1(), test5_16(), test5_2(), test5_4(), test5_8(), test6_16(), test6_64(), test7_1(), test7_2(), test7_4(), test7_8(), test8_1(), test8_2(), test8_4(), test8_8(), test9_1(), test9_4(), testA(), testB(), testC(), testD(), and testE().
template<typename T , int Size> void DumpListFlat (const BList< T, Size > & blist)
Definition at line 81 of file driver.cpp.
References BList< T, Size >::BNode::count, BList< T, Size >::GetHead(), BList< T, Size >::BNode::next, and BList< T, Size >::BNode::values.
template<typename T , int Size> void DumpStats (const BList< T, Size > & blist)
Definition at line 32 of file driver.cpp.
References BListStats::ArraySize, BList< T, Size >::GetStats(), BListStats::ItemCount, and BListStats::NodeCount.
Referenced by test10_1(), test10_4(), test11_8(), test12_8(), test1_1(), test1_16(), test1_2(), test1_4(), test1_8(), test2(), test2_1(), test2_16(), test2_2(), test2_4(), test2_8(), test3_1(), test3_16(), test3_2(), test3_4(), test3_8(), test4_1(), test4_16(), test4_2(), test4_4(), test4_8(), test5_1(), test5_16(), test5_2(), test5_4(), test5_8(), test6_16(), test6_512(), test6_64(), test9_1(), and test9_4().
int main (int argc, char ** argv)
Definition at line 1675 of file driver.cpp.
References test10_1(), test10_4(), test11_8(), test12_8(), test1_1(), test1_16(), test1_2(), test1_4(), test1_8(), test2_1(), test2_16(), test2_2(), test2_4(), test2_8(), test3_1(), test3_16(), test3_2(), test3_4(), test3_8(), test4_1(), test4_16(), test4_2(), test4_4(), test4_8(), test5_1(), test5_16(), test5_2(), test5_4(), test5_8(), test6_16(), test6_512(), test6_64(), test7_1(), test7_2(), test7_4(), test7_8(), test8_1(), test8_2(), test8_4(), test8_8(), test9_1(), test9_4(), testA(), testB(), testC(), and testD().
std::ostream& operator<< (std::ostream & os, const Foo & rhs)
Definition at line 1530 of file driver.cpp.
References Foo::a, and Foo::b.
template<typename T , int Size> void print_subscript (const BList< T, Size > & list)
Definition at line 455 of file driver.cpp.
References BList< T, Size >::size().
Referenced by test4_1().
int RandomInt (int low, int high)
Definition at line 8 of file driver.cpp.
References Digipen::Utils::Random().
Referenced by Shuffle().
template<typename T > void Shuffle (T * array, int count)
Definition at line 22 of file driver.cpp.
References RandomInt(), and SwapT().
Referenced by test10_1(), test10_4(), test11_8(), test12_8(), test3_1(), test3_16(), test3_2(), test3_4(), test3_8(), test4_1(), test4_16(), test4_2(), test4_4(), test4_8(), test5_1(), test5_16(), test5_2(), test5_4(), test5_8(), test6_16(), test6_512(), test6_64(), test7_1(), test7_2(), test7_4(), test7_8(), test8_1(), test8_2(), test8_4(), test8_8(), test9_1(), and test9_4().
template<typename T > void SwapT (T & a, T & b)
Definition at line 14 of file driver.cpp.
Referenced by Shuffle().
void test1 ()
Definition at line 1482 of file driver.cpp.
References DumpList(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), and Digipen::Utils::srand().
void test10_1 ()
Definition at line 1321 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test10_4 ()
Definition at line 1360 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test11_8 ()
Definition at line 1399 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test12_8 ()
Definition at line 1438 of file driver.cpp.
References BList< T, Size >::clear(), DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test1_1 ()
Definition at line 97 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_front().
Referenced by main().
void test1_16 ()
Definition at line 173 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_front().
Referenced by main().
void test1_2 ()
Definition at line 116 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_front().
Referenced by main().
void test1_4 ()
Definition at line 135 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_front().
Referenced by main().
void test1_8 ()
Definition at line 154 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_front().
Referenced by main().
void test2 ()
Definition at line 1536 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::find(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), BList< T, Size >::remove(), BList< T, Size >::remove_by_value(), and Digipen::Utils::srand().
void test2_1 ()
Definition at line 195 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_back().
Referenced by main().
void test2_16 ()
Definition at line 271 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_back().
Referenced by main().
void test2_2 ()
Definition at line 214 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_back().
Referenced by main().
void test2_4 ()
Definition at line 233 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_back().
Referenced by main().
void test2_8 ()
Definition at line 252 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::nodesize(), and BList< T, Size >::push_back().
Referenced by main().
void test3_1 ()
Definition at line 294 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test3_16 ()
Definition at line 418 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test3_2 ()
Definition at line 325 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test3_4 ()
Definition at line 356 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test3_8 ()
Definition at line 387 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test4_1 ()
Definition at line 463 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), print_subscript(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test4_16 ()
Definition at line 616 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test4_2 ()
Definition at line 499 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test4_4 ()
Definition at line 538 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test4_8 ()
Definition at line 577 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test5_1 ()
Definition at line 658 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::find(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), and Shuffle().
Referenced by main().
void test5_16 ()
Definition at line 806 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::find(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), and Shuffle().
Referenced by main().
void test5_2 ()
Definition at line 695 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::find(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), and Shuffle().
Referenced by main().
void test5_4 ()
Definition at line 732 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::find(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), and Shuffle().
Referenced by main().
void test5_8 ()
Definition at line 769 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::find(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), and Shuffle().
Referenced by main().
void test6_16 ()
Definition at line 847 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::find(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), and Shuffle().
Referenced by main().
void test6_512 ()
Definition at line 926 of file driver.cpp.
References DumpStats(), BList< T, Size >::find(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), and Shuffle().
Referenced by main().
void test6_64 ()
Definition at line 888 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::find(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), and Shuffle().
Referenced by main().
void test7_1 ()
Definition at line 967 of file driver.cpp.
References DumpList(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), BList< T, Size >::remove(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test7_2 ()
Definition at line 1002 of file driver.cpp.
References DumpList(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), BList< T, Size >::remove(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test7_4 ()
Definition at line 1037 of file driver.cpp.
References DumpList(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), BList< T, Size >::remove(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test7_8 ()
Definition at line 1072 of file driver.cpp.
References DumpList(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), BList< T, Size >::remove(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test8_1 ()
Definition at line 1112 of file driver.cpp.
References DumpList(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), BList< T, Size >::remove_by_value(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test8_2 ()
Definition at line 1145 of file driver.cpp.
References DumpList(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), BList< T, Size >::remove_by_value(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test8_4 ()
Definition at line 1178 of file driver.cpp.
References DumpList(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), BList< T, Size >::remove_by_value(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test8_8 ()
Definition at line 1211 of file driver.cpp.
References DumpList(), BList< T, Size >::nodesize(), BList< T, Size >::push_back(), BList< T, Size >::remove_by_value(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test9_1 ()
Definition at line 1245 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void test9_4 ()
Definition at line 1283 of file driver.cpp.
References DumpList(), DumpStats(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), Shuffle(), and Digipen::Utils::srand().
Referenced by main().
void testA ()
Definition at line 1578 of file driver.cpp.
References DumpList(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), BList< T, Size >::remove(), and Digipen::Utils::srand().
Referenced by main().
void testB ()
Definition at line 1599 of file driver.cpp.
References DumpList(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), and Digipen::Utils::srand().
Referenced by main().
void testC ()
Definition at line 1620 of file driver.cpp.
References DumpList(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), and Digipen::Utils::srand().
Referenced by main().
void testD ()
Definition at line 1640 of file driver.cpp.
References DumpList(), BList< T, Size >::insert(), BList< T, Size >::nodesize(), and Digipen::Utils::srand().
Referenced by main().
void testE ()
Definition at line 1658 of file driver.cpp.
References DumpList(), and BList< T, Size >::insert().