ALGraph Class Reference
ALGraph Class Reference
#include <ALGraph.h>
Classes
struct AdjInfo
struct GNode
Public Types
enum TRAVERSAL_METHOD { DEPTH_FIRST, BREADTH_FIRST }
Public Member Functions
ALGraph (unsigned size)
~ALGraph ()
void AddDEdge (unsigned source, unsigned destination, unsigned weight)
void AddUEdge (unsigned node1, unsigned node2, unsigned weight)
std::vector< unsigned > SearchFrom (unsigned start_node, TRAVERSAL_METHOD method) const
std::vector< DijkstraInfo > Dijkstra (unsigned start_node) const
ALIST GetAList () const
Static Public Member Functions
static bool ImplementedSearches ()
Private Attributes
ALIST alist
Detailed Description
Definition at line 38 of file ALGraph.h.
Member Enumeration Documentation
enum ALGraph::TRAVERSAL_METHOD
Enumerator:
DEPTH_FIRST
BREADTH_FIRST
Definition at line 41 of file ALGraph.h.
Constructor & Destructor Documentation
ALGraph::ALGraph (unsigned size)
Constructor for an ALGraph
Author:
louis.coyleii
Date:
11/23/14
Parameters:
size The number of nodes for the graph to construct.
Definition at line 34 of file ALGraph.cpp.
References alist.
ALGraph::~ALGraph (void)
Destructor for an ALGraph
Author:
louis.coyleii
Date:
11/23/14
Definition at line 53 of file ALGraph.cpp.
References alist.
Member Function Documentation
void ALGraph::AddDEdge (unsigned source, unsigned destination, unsigned weight)
Adds a directed edge to the graph.
Author:
louis.coyleii
Date:
11/23/14
Parameters:
source Where the edge starts from.
destination Where the edge ends up.
weight The cost of the edge.
Definition at line 71 of file ALGraph.cpp.
References alist.
Referenced by AddUEdge(), TestBig(), TestDijkstra4(), TestDijkstra4a(), TestSearch1(), and TestSearch2().
void ALGraph::AddUEdge (unsigned node1, unsigned node2, unsigned weight)
Adds an undirected edge to the graph.
Author:
louis.coyleii
Date:
11/23/14
Parameters:
node1 One endpoint of the edge.
node2 The other endpoint of the edge.
weight The cost of the edge.
Definition at line 115 of file ALGraph.cpp.
References AddDEdge().
Referenced by TestDijkstra0(), TestDijkstra1(), TestDijkstra10(), TestDijkstra5(), and TestDijkstra9().
std::vector< DijkstraInfo > ALGraph::Dijkstra (unsigned start_node) const
Searches the graph, constructing a list of paths and costs, using Dijkstra.
Author:
louis.coyleii
Date:
11/23/14
Parameters:
start_node The node to start the search from.
Returns:
std::vector<DijkstraInfo> The list of paths and costs.
Definition at line 160 of file ALGraph.cpp.
References alist, ALGraph::GNode::evaluated, ALGraph::GNode::id, and ALGraph::AdjInfo::node.
Referenced by TestBig(), TestDijkstra0(), TestDijkstra1(), TestDijkstra10(), TestDijkstra4(), TestDijkstra4a(), TestDijkstra5(), and TestDijkstra9().
ALIST ALGraph::GetAList (void) const
Gets an adjacency list for the graph.
Author:
louis.coyleii
Date:
11/23/14
Returns:
ALIST The adjacency list.
Definition at line 258 of file ALGraph.cpp.
References alist.
Referenced by TestBig(), TestDijkstra0(), TestDijkstra1(), TestDijkstra10(), TestDijkstra4(), TestDijkstra4a(), TestDijkstra5(), TestDijkstra9(), TestSearch1(), and TestSearch2().
bool ALGraph::ImplementedSearches (void) [static]
Returns true if searches were implemented.
Author:
louis.coyleii
Date:
11/23/14
Returns:
bool Whether or not searches were implemented.
Definition at line 274 of file ALGraph.cpp.
Referenced by TestAllSearch1(), TestAllSearch2(), TestSearch1(), and TestSearch2().
std::vector< unsigned > ALGraph::SearchFrom (unsigned start_node, TRAVERSAL_METHOD method) const
Searches the graph, constructing a list of paths and costs.
Author:
louis.coyleii
Date:
11/23/14
Parameters:
start_node The node to start the search from.
method How the graph should be traversed.
Returns:
std::vector<unsigned> The list of paths and costs.
Definition at line 137 of file ALGraph.cpp.
Referenced by TestSearch1(), and TestSearch2().
Member Data Documentation
ALIST ALGraph::alist [private]
Definition at line 68 of file ALGraph.h.
Referenced by AddDEdge(), ALGraph(), Dijkstra(), GetAList(), and ~ALGraph().
The documentation for this class was generated from the following files:
ALGraph.h
ALGraph.cpp