ObjectAllocator Class Reference
ObjectAllocator Class Reference
#include <ObjectAllocator.h>
Public Types
typedef void(* DUMPCALLBACK)(const void *, size_t)
typedef void(* VALIDATECALLBACK)(const void *, size_t)
Public Member Functions
ObjectAllocator (size_t ObjectSize, const OAConfig &config) NOEXCEPT(false)
Creates the ObjectManager per the specified values. Throws an exception if the construction fails. (Memory allocation problem)
~ObjectAllocator () NOEXCEPT(true)
Destroys the ObjectManager. (never throws)
void * Allocate (const char *label=0) NOEXCEPT(false)
Take an object from the free list and give it to the client. (simulates new) Throws an exception if the object can't be allocated. (Memory allocation problem)
void Free (void *Object) NOEXCEPT(false)
Returns an object to the free list for the client. (simulates delete) Throws an exception if the the object can't be freed. (Invalid object)
unsigned DumpMemoryInUse (DUMPCALLBACK fn) const
Calls the callback fn for each block still in use.
unsigned ValidatePages (VALIDATECALLBACK fn) const
Calls the callback fn for each block that is potentially corrupted.
unsigned FreeEmptyPages (void)
Frees all empty pages. (extra credit)
void SetDebugState (bool State)
Sets the debug state, true=enable, false=disable.
const void * GetFreeList (void) const
Returns a pointer to the internal free list.
const void * GetPageList (void) const
Returns a pointer to the internal page list.
OAConfig GetConfig (void) const
Returns the configuration parameters.
OAStats GetStats (void) const
Returns the statistics for the allocator.
Static Public Member Functions
static bool ImplementedExtraCredit (void)
Returns true if FreeEmptyPages and alignments are implemented.
Static Public Attributes
static const unsigned char UNALLOCATED_PATTERN = 0xAA
static const unsigned char ALLOCATED_PATTERN = 0xBB
static const unsigned char FREED_PATTERN = 0xCC
static const unsigned char PAD_PATTERN = 0xDD
static const unsigned char ALIGN_PATTERN = 0xEE
Private Types
typedef unsigned char byte_t
Private Member Functions
ObjectAllocator (const ObjectAllocator &oa)
ObjectAllocator & operator= (const ObjectAllocator &oa)
void ExpandPages (void) NOEXCEPT(false)
Helper function to create a new page when freelist is empty.
bool CheckIfFree (void *Object) const
Helper function to check for free blocks.
byte_t * increment_head (byte_t *head) const
Increments a linked list.
void push_front (byte_t *&head, byte_t *newhead)
Pushes a node to the front of the linked list.
void setup_header (void)
Initializes the headers appropriately based on their type.
void update_header (bool inuse, byte_t *Object, const char *label=0)
Updates the header based on the header type.
bool validate_object (byte_t const *Object) const
Validates that the page is not corrupted.
void delete_memblock (void *Object)
Deletes the external header block associated with the object.
Private Attributes
unsigned node_size
unsigned offset
OAConfig oaconfig
OAStats oastats
byte_t * FreeList
byte_t * PageList
Detailed Description
Definition at line 148 of file ObjectAllocator.h.
Member Typedef Documentation
typedef unsigned char ObjectAllocator::byte_t [private]
Definition at line 197 of file ObjectAllocator.h.
typedef void(* ObjectAllocator::DUMPCALLBACK)(const void *, size_t)
Definition at line 152 of file ObjectAllocator.h.
typedef void(* ObjectAllocator::VALIDATECALLBACK)(const void *, size_t)
Definition at line 153 of file ObjectAllocator.h.
Constructor & Destructor Documentation
ObjectAllocator::ObjectAllocator (size_t ObjectSize, const OAConfig & config)
Creates the ObjectManager per the specified values. Throws an exception if the construction fails. (Memory allocation problem)
Parameters:
ObjectSize The size of the objects to be managed.
config The configuration paramaters for the manager to be constructed.
Definition at line 42 of file ObjectAllocator.cpp.
ObjectAllocator::~ObjectAllocator ()
Destroys the ObjectManager. (never throws)
Definition at line 78 of file ObjectAllocator.cpp.
References delete_memblock(), OAConfig::hbExternal, OAConfig::HBlockInfo_, increment_head(), node_size, oaconfig, oastats, offset, PageList, and OAStats::PageSize_.
ObjectAllocator::ObjectAllocator (const ObjectAllocator & oa) [private]
Member Function Documentation
void * ObjectAllocator::Allocate (const char * label = 0)
Take an object from the free list and give it to the client. (simulates new) Throws an exception if the object can't be allocated. (Memory allocation problem)
Parameters:
label The name of the block of memory to be allocated.
Returns:
void* The allocated block of memory.
Definition at line 128 of file ObjectAllocator.cpp.
References OAException::E_NO_MEMORY.
Referenced by DisableOA(), DoEmployees(), DoStudents(), Stress(), StressFreeChecking(), TestAlignment(), TestBasicHeaderBlocks(), TestCorruption(), TestExtendedHeaderBlocks(), TestExternalHeaderBlocks(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), TestFreeEmptyPages4(), TestLeak(), and TestValidate().
bool ObjectAllocator::CheckIfFree (void * Object) const [private]
Helper function to check for free blocks.
Parameters:
Object The object to check if free.
Returns:
bool Whether or not the supplied block was on freelist.
Definition at line 526 of file ObjectAllocator.cpp.
References FreeList, OAConfig::hbBasic, OAConfig::hbExtended, OAConfig::hbExternal, OAConfig::HBlockInfo_, OAConfig::hbNone, increment_head(), oaconfig, offset, and OAConfig::PadBytes_.
Referenced by DumpMemoryInUse().
void ObjectAllocator::delete_memblock (void * Object) [private]
Deletes the external header block associated with the object.
Parameters:
Object The object to validate.
Definition at line 842 of file ObjectAllocator.cpp.
References MemBlockInfo::label, and offset.
Referenced by ~ObjectAllocator().
unsigned ObjectAllocator::DumpMemoryInUse (DUMPCALLBACK fn) const
Calls the callback fn for each block still in use.
Parameters:
fn A pointer to the callback fn for the block still in use.
Returns:
unsigned The number of blocks that are in use by the client.
Definition at line 269 of file ObjectAllocator.cpp.
References CheckIfFree(), increment_head(), node_size, oastats, OAStats::ObjectSize_, offset, PageList, and OAStats::PageSize_.
Referenced by CheckAndDumpLeaks(), and StressFreeChecking().
void ObjectAllocator::ExpandPages (void) [private]
Helper function to create a new page when freelist is empty.
Definition at line 470 of file ObjectAllocator.cpp.
References OAConfig::DebugOn_, OAException::E_NO_MEMORY, OAException::E_NO_PAGES, FreeList, OAStats::FreeObjects_, OAConfig::HBlockInfo_, OAConfig::MaxPages_, node_size, oaconfig, oastats, OAStats::ObjectSize_, OAConfig::ObjectsPerPage_, offset, PAD_PATTERN, OAConfig::PadBytes_, PageList, OAStats::PagesInUse_, OAStats::PageSize_, push_front(), and UNALLOCATED_PATTERN.
void ObjectAllocator::Free (void * Object)
Returns an object to the free list for the client. (simulates delete) Throws an exception if the the object can't be freed. (Invalid object)
Parameters:
Object The object to be freed.
Definition at line 197 of file ObjectAllocator.cpp.
References OAException::E_BAD_BOUNDARY, OAException::E_CORRUPTED_BLOCK, and OAException::E_MULTIPLE_FREE.
Referenced by DisableOA(), DoEmployees(), DoStudents(), Stress(), StressFreeChecking(), TestBasicHeaderBlocks(), TestCorruption(), TestExtendedHeaderBlocks(), TestExternalHeaderBlocks(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), TestFreeEmptyPages4(), and TestLeak().
unsigned ObjectAllocator::FreeEmptyPages (void)
Frees all empty pages. (extra credit)
Returns:
unsigned The number of pages that were freed.
Definition at line 358 of file ObjectAllocator.cpp.
Referenced by TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), and TestFreeEmptyPages4().
OAConfig ObjectAllocator::GetConfig (void) const
Returns the configuration parameters.
Returns:
OAConfig The configuration paramaters struct.
Definition at line 441 of file ObjectAllocator.cpp.
References oaconfig.
Referenced by DumpExternalHeaders(), DumpPages(), DumpPagesEx(), PrintConfig(), and TestLeak().
const void * ObjectAllocator::GetFreeList (void) const
Returns a pointer to the internal free list.
Returns:
const void * A pointer to the internal free list.
Definition at line 409 of file ObjectAllocator.cpp.
References FreeList.
const void * ObjectAllocator::GetPageList (void) const
Returns a pointer to the internal page list.
Returns:
const void * A pointer to the internal page list.
Definition at line 425 of file ObjectAllocator.cpp.
References PageList.
Referenced by DumpPages(), and DumpPagesEx().
OAStats ObjectAllocator::GetStats (void) const
Returns the statistics for the allocator.
Returns:
OAStats The statistics for the allocator.
Definition at line 457 of file ObjectAllocator.cpp.
References oastats.
Referenced by CheckAndDumpLeaks(), DisableOA(), DoEmployees(), DoStudents(), DumpExternalHeaders(), DumpPages(), PrintConfig(), PrintCounts(), PrintCounts2(), and TestLeak().
bool ObjectAllocator::ImplementedExtraCredit (void) [static]
Returns true if FreeEmptyPages and alignments are implemented.
Returns:
static bool A boolean, indicating whether or not the extra credit has been implemented.
Definition at line 374 of file ObjectAllocator.cpp.
Referenced by TestAlignment(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), and TestFreeEmptyPages4().
ObjectAllocator::byte_t * ObjectAllocator::increment_head (byte_t * head) const [private]
Increments a linked list.
Parameters:
head The head of the list to increment.
Returns:
ObjectAllocator::byte_t* The next node in the list.
Definition at line 591 of file ObjectAllocator.cpp.
References GenericObject::Next.
Referenced by CheckIfFree(), DumpMemoryInUse(), setup_header(), ValidatePages(), and ~ObjectAllocator().
ObjectAllocator& ObjectAllocator::operator= (const ObjectAllocator & oa) [private]
void ObjectAllocator::push_front (byte_t *& head, byte_t * newhead) [private]
Pushes a node to the front of the linked list.
Parameters:
head The head of the list to push onto.
newhead The new head to push onto the list.
Definition at line 613 of file ObjectAllocator.cpp.
References GenericObject::Next.
Referenced by ExpandPages().
void ObjectAllocator::SetDebugState (bool State)
Sets the debug state, true=enable, false=disable.
Parameters:
State A boolean, indicating whether or not to set debug state on.
Definition at line 393 of file ObjectAllocator.cpp.
References OAConfig::DebugOn_, and oaconfig.
void ObjectAllocator::setup_header (void) [private]
Initializes the headers appropriately based on their type.
Definition at line 630 of file ObjectAllocator.cpp.
References FreeList, OAConfig::hbBasic, OAConfig::hbExtended, OAConfig::hbExternal, OAConfig::HBlockInfo_, OAConfig::hbNone, increment_head(), MemBlockInfo::label, oaconfig, offset, and PageList.
void ObjectAllocator::update_header (bool inuse, byte_t * Object, const char * label = 0) [private]
Updates the header based on the header type.
Parameters:
inuse Whether or not the object is in use
Object The object to update header for.
label Label for the object, for use in external header blocks.
Definition at line 705 of file ObjectAllocator.cpp.
References OAStats::Allocations_, OAException::E_NO_MEMORY, OAConfig::hbBasic, OAConfig::hbExtended, OAConfig::hbExternal, OAConfig::HBlockInfo_, OAConfig::hbNone, MemBlockInfo::in_use, oaconfig, oastats, offset, and OAConfig::PadBytes_.
bool ObjectAllocator::validate_object (byte_t const * Object) const [private]
Validates that the page is not corrupted.
Parameters:
Object The object to validate.
Returns:
bool Returns false if object was corrupted.
Definition at line 805 of file ObjectAllocator.cpp.
References oaconfig, oastats, OAStats::ObjectSize_, PAD_PATTERN, and OAConfig::PadBytes_.
Referenced by ValidatePages().
unsigned ObjectAllocator::ValidatePages (VALIDATECALLBACK fn) const
Calls the callback fn for each block that is potentially corrupted.
Parameters:
fn A pointer to the callback fn for the block that is potentially corrupted.
Returns:
unsigned The number of blocks that are corrupted.
Definition at line 315 of file ObjectAllocator.cpp.
References increment_head(), node_size, oastats, OAStats::ObjectSize_, offset, PageList, OAStats::PageSize_, and validate_object().
Referenced by TestValidate().
Member Data Documentation
const unsigned char ObjectAllocator::ALIGN_PATTERN = 0xEE [static]
Definition at line 160 of file ObjectAllocator.h.
const unsigned char ObjectAllocator::ALLOCATED_PATTERN = 0xBB [static]
Definition at line 157 of file ObjectAllocator.h.
const unsigned char ObjectAllocator::FREED_PATTERN = 0xCC [static]
Definition at line 158 of file ObjectAllocator.h.
byte_t* ObjectAllocator::FreeList [private]
Definition at line 216 of file ObjectAllocator.h.
Referenced by CheckIfFree(), ExpandPages(), GetFreeList(), and setup_header().
unsigned ObjectAllocator::node_size [private]
Definition at line 212 of file ObjectAllocator.h.
Referenced by DumpMemoryInUse(), ExpandPages(), ValidatePages(), and ~ObjectAllocator().
OAConfig ObjectAllocator::oaconfig [private]
Definition at line 214 of file ObjectAllocator.h.
Referenced by CheckIfFree(), ExpandPages(), GetConfig(), SetDebugState(), setup_header(), update_header(), validate_object(), and ~ObjectAllocator().
OAStats ObjectAllocator::oastats [private]
Definition at line 215 of file ObjectAllocator.h.
Referenced by DumpMemoryInUse(), ExpandPages(), GetStats(), update_header(), validate_object(), ValidatePages(), and ~ObjectAllocator().
unsigned ObjectAllocator::offset [private]
Definition at line 213 of file ObjectAllocator.h.
Referenced by CheckIfFree(), delete_memblock(), DumpMemoryInUse(), ExpandPages(), setup_header(), update_header(), ValidatePages(), and ~ObjectAllocator().
const unsigned char ObjectAllocator::PAD_PATTERN = 0xDD [static]
Definition at line 159 of file ObjectAllocator.h.
Referenced by ExpandPages(), and validate_object().
byte_t* ObjectAllocator::PageList [private]
Definition at line 217 of file ObjectAllocator.h.
Referenced by DumpMemoryInUse(), ExpandPages(), GetPageList(), setup_header(), ValidatePages(), and ~ObjectAllocator().
const unsigned char ObjectAllocator::UNALLOCATED_PATTERN = 0xAA [static]
Definition at line 156 of file ObjectAllocator.h.
Referenced by ExpandPages().
The documentation for this class was generated from the following files:
ObjectAllocator.h
ObjectAllocator.cpp