driver-sample.cpp File Reference
driver-sample.cpp File Reference
#include <iostream>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include "ObjectAllocator.h"
#include "PRNG.h"
#include <ctime>
Classes
struct Student
struct Employee
struct Person
Functions
void PrintCounts (const ObjectAllocator *nm)
void PrintCounts2 (const ObjectAllocator *nm)
void PrintConfig (const ObjectAllocator *nm)
void DumpPages (const ObjectAllocator *nm, unsigned width=16)
void DumpPagesEx (const ObjectAllocator *nm, unsigned width=16)
void DoStudents (unsigned padding=0, bool printall=false)
void DoEmployees (void)
void TestPadding (unsigned size)
void TestBasicHeaderBlocks ()
void TestCorruption (void)
void DisableOA (void)
void TestLeak (void)
void TestValidate (void)
void TestAlignment (void)
void TestFreeEmptyPages1 (void)
void TestFreeEmptyPages2 (void)
void TestFreeEmptyPages3 (void)
void StressFreeChecking (void)
void Stress (bool UseNewDelete)
void FillEmployee (Employee &emp)
void DumpCallback (const void *block, size_t actual_size)
void DumpCallback2 (const void *, size_t)
void CheckAndDumpLeaks (const ObjectAllocator *oa)
void ValidateCallback (const void *block, size_t actual_size)
int RandomInt (int low, int high)
template<typename T >
void SwapT (T &a, T &b)
template<typename T >
void Shuffle (T *array, unsigned count)
template<typename T >
void PrintArray (T *array, unsigned count)
void StressFreeChecking (const OAConfig::HeaderBlockInfo &header)
void TestFreeEmptyPages4 (void)
void TestExtendedHeaderBlocks (unsigned size)
void TestExternalHeaderBlocks ()
void DumpExternalHeaders (const ObjectAllocator *oa, const unsigned char *p)
void Test1 (void)
int main (int argc, char **argv)
Variables
int SHOWADDRESS1 = 0
int SHOWADDRESS2 = 0
int SHOWREAL = 0
int SHOW_EXCEPTIONS = 0
int EXTRA_CREDIT = 0
ObjectAllocator * studentObjectMgr
ObjectAllocator * employeeObjectMgr
struct Person PEOPLE []
const unsigned objects = 4096
const unsigned pages = 100
const unsigned total = objects * pages
void * ptrs [total]
Function Documentation
void CheckAndDumpLeaks (const ObjectAllocator * oa)
Definition at line 148 of file driver-sample.cpp.
References DumpCallback(), ObjectAllocator::DumpMemoryInUse(), ObjectAllocator::GetStats(), and OAStats::ObjectsInUse_.
Referenced by TestLeak().
void DisableOA (void)
Definition at line 1279 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), ObjectAllocator::Free(), ObjectAllocator::GetStats(), OAConfig::hbNone, OAStats::MostObjects_, PrintConfig(), PrintCounts2(), SHOW_EXCEPTIONS, studentObjectMgr, and OAException::what().
void DoEmployees (void)
Definition at line 1139 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), employeeObjectMgr, ObjectAllocator::Free(), ObjectAllocator::GetStats(), OAConfig::hbNone, OAStats::MostObjects_, PrintConfig(), PrintCounts(), SHOW_EXCEPTIONS, and OAException::what().
void DoStudents (unsigned padding = 0, bool printall = false)
Definition at line 1011 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpPages(), ObjectAllocator::Free(), ObjectAllocator::GetStats(), OAConfig::hbNone, OAStats::MostObjects_, PrintConfig(), PrintCounts(), SHOW_EXCEPTIONS, studentObjectMgr, and OAException::what().
Referenced by TestPadding().
void DumpCallback (const void * block, size_t actual_size)
Definition at line 109 of file driver-sample.cpp.
References SHOWADDRESS1.
Referenced by CheckAndDumpLeaks().
void DumpCallback2 (const void * , size_t)
Definition at line 144 of file driver-sample.cpp.
Referenced by StressFreeChecking().
void DumpExternalHeaders (const ObjectAllocator * oa, const unsigned char * p)
Definition at line 1966 of file driver-sample.cpp.
References MemBlockInfo::alloc_num, ObjectAllocator::GetConfig(), ObjectAllocator::GetStats(), OAConfig::HBlockInfo_, MemBlockInfo::in_use, OAConfig::InterAlignSize_, MemBlockInfo::label, OAConfig::LeftAlignSize_, OAStats::ObjectSize_, OAConfig::ObjectsPerPage_, and OAConfig::PadBytes_.
void DumpPages (const ObjectAllocator * nm, unsigned width = 16)
Definition at line 1834 of file driver-sample.cpp.
References OAConfig::Alignment_, ObjectAllocator::GetConfig(), ObjectAllocator::GetPageList(), ObjectAllocator::GetStats(), OAConfig::HBlockInfo_, OAConfig::InterAlignSize_, OAConfig::LeftAlignSize_, OAStats::ObjectSize_, OAConfig::ObjectsPerPage_, OAConfig::PadBytes_, pages, and SHOWREAL.
Referenced by DoStudents(), TestAlignment(), TestBasicHeaderBlocks(), TestCorruption(), TestExtendedHeaderBlocks(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), TestFreeEmptyPages4(), and TestValidate().
void DumpPagesEx (const ObjectAllocator * nm, unsigned width = 16)
Definition at line 1997 of file driver-sample.cpp.
References OAConfig::Alignment_, ObjectAllocator::GetConfig(), ObjectAllocator::GetPageList(), OAConfig::HBlockInfo_, OAConfig::InterAlignSize_, OAConfig::LeftAlignSize_, OAConfig::ObjectsPerPage_, pages, and SHOWREAL.
Referenced by TestExternalHeaderBlocks().
void FillEmployee (Employee & emp)
Definition at line 96 of file driver-sample.cpp.
References Person::firstName, Employee::firstName, Person::lastName, Employee::lastName, Person::salary, Employee::salary, Person::years, and Employee::years.
Referenced by TestLeak().
int main (int argc, char ** argv)
Definition at line 2161 of file driver-sample.cpp.
template<typename T > void PrintArray (T * array, unsigned count)
Definition at line 199 of file driver-sample.cpp.
void PrintConfig (const ObjectAllocator * nm)
Definition at line 1809 of file driver-sample.cpp.
References OAConfig::Alignment_, ObjectAllocator::GetConfig(), ObjectAllocator::GetStats(), OAConfig::hbBasic, OAConfig::hbExtended, OAConfig::hbExternal, OAConfig::HBlockInfo_, OAConfig::hbNone, OAConfig::InterAlignSize_, OAConfig::LeftAlignSize_, OAConfig::MaxPages_, OAStats::ObjectSize_, OAConfig::ObjectsPerPage_, OAConfig::PadBytes_, and OAStats::PageSize_.
Referenced by DisableOA(), DoEmployees(), DoStudents(), StressFreeChecking(), TestAlignment(), TestBasicHeaderBlocks(), TestCorruption(), TestExtendedHeaderBlocks(), TestExternalHeaderBlocks(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), TestFreeEmptyPages4(), TestLeak(), and TestValidate().
void PrintCounts (const ObjectAllocator * nm)
Definition at line 1792 of file driver-sample.cpp.
References OAStats::Allocations_, OAStats::Deallocations_, OAStats::FreeObjects_, ObjectAllocator::GetStats(), OAStats::ObjectsInUse_, and OAStats::PagesInUse_.
Referenced by DoEmployees(), DoStudents(), StressFreeChecking(), TestAlignment(), TestBasicHeaderBlocks(), TestCorruption(), TestExtendedHeaderBlocks(), TestExternalHeaderBlocks(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), TestFreeEmptyPages4(), TestLeak(), and TestValidate().
void PrintCounts2 (const ObjectAllocator * nm)
Definition at line 1802 of file driver-sample.cpp.
References OAStats::Allocations_, OAStats::Deallocations_, and ObjectAllocator::GetStats().
Referenced by DisableOA().
int RandomInt (int low, int high)
Definition at line 174 of file driver-sample.cpp.
References Digipen::Utils::Random().
Referenced by Shuffle().
template<typename T > void Shuffle (T * array, unsigned count)
Definition at line 189 of file driver-sample.cpp.
References RandomInt(), and SwapT().
Referenced by Stress(), StressFreeChecking(), TestFreeEmptyPages3(), and TestFreeEmptyPages4().
void Stress (bool UseNewDelete)
Definition at line 211 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), ObjectAllocator::Free(), OAConfig::hbNone, objects, pages, ptrs, SHOW_EXCEPTIONS, Shuffle(), total, and OAException::what().
void StressFreeChecking (void)
void StressFreeChecking (const OAConfig::HeaderBlockInfo & header)
Definition at line 250 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpCallback2(), ObjectAllocator::DumpMemoryInUse(), ObjectAllocator::Free(), objects, pages, PrintConfig(), PrintCounts(), ptrs, SHOW_EXCEPTIONS, Shuffle(), total, and OAException::what().
template<typename T > void SwapT (T & a, T & b)
Definition at line 181 of file driver-sample.cpp.
Referenced by Shuffle().
void Test1 (void)
Definition at line 2138 of file driver-sample.cpp.
void TestAlignment (void)
Definition at line 1743 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpPages(), OAConfig::hbBasic, ObjectAllocator::ImplementedExtraCredit(), PrintConfig(), PrintCounts(), SHOW_EXCEPTIONS, and OAException::what().
void TestBasicHeaderBlocks ()
Definition at line 593 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpPages(), ObjectAllocator::Free(), OAConfig::hbBasic, PrintConfig(), PrintCounts(), SHOW_EXCEPTIONS, and OAException::what().
void TestCorruption (void)
Definition at line 1402 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), OAException::code(), DumpPages(), OAException::E_CORRUPTED_BLOCK, ObjectAllocator::Free(), OAConfig::hbBasic, PrintConfig(), PrintCounts(), SHOW_EXCEPTIONS, and OAException::what().
void TestExtendedHeaderBlocks (unsigned size)
Definition at line 717 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpPages(), ObjectAllocator::Free(), OAConfig::hbExtended, PrintConfig(), PrintCounts(), SHOW_EXCEPTIONS, and OAException::what().
void TestExternalHeaderBlocks ()
Definition at line 898 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpPagesEx(), ObjectAllocator::Free(), OAConfig::hbExternal, PrintConfig(), PrintCounts(), SHOW_EXCEPTIONS, and OAException::what().
void TestFreeEmptyPages1 (void)
Definition at line 308 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpPages(), ObjectAllocator::Free(), ObjectAllocator::FreeEmptyPages(), OAConfig::hbNone, ObjectAllocator::ImplementedExtraCredit(), objects, pages, PrintConfig(), PrintCounts(), ptrs, SHOW_EXCEPTIONS, total, and OAException::what().
void TestFreeEmptyPages2 (void)
Definition at line 399 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpPages(), ObjectAllocator::Free(), ObjectAllocator::FreeEmptyPages(), OAConfig::hbBasic, ObjectAllocator::ImplementedExtraCredit(), objects, pages, PrintConfig(), PrintCounts(), ptrs, SHOW_EXCEPTIONS, total, and OAException::what().
void TestFreeEmptyPages3 (void)
Definition at line 473 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpPages(), ObjectAllocator::Free(), ObjectAllocator::FreeEmptyPages(), OAConfig::hbExtended, ObjectAllocator::ImplementedExtraCredit(), objects, pages, PrintConfig(), PrintCounts(), ptrs, SHOW_EXCEPTIONS, Shuffle(), total, and OAException::what().
void TestFreeEmptyPages4 (void)
Definition at line 531 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), DumpPages(), ObjectAllocator::Free(), ObjectAllocator::FreeEmptyPages(), OAConfig::hbExtended, ObjectAllocator::ImplementedExtraCredit(), objects, pages, PrintConfig(), PrintCounts(), ptrs, SHOW_EXCEPTIONS, Shuffle(), total, and OAException::what().
void TestLeak (void)
Definition at line 1496 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), CheckAndDumpLeaks(), employeeObjectMgr, FillEmployee(), ObjectAllocator::Free(), ObjectAllocator::GetConfig(), ObjectAllocator::GetStats(), OAConfig::hbBasic, OAConfig::MaxPages_, OAStats::MostObjects_, OAConfig::ObjectsPerPage_, PrintConfig(), PrintCounts(), SHOW_EXCEPTIONS, and OAException::what().
void TestPadding (unsigned size)
Definition at line 1132 of file driver-sample.cpp.
References DoStudents().
void TestValidate (void)
Definition at line 1606 of file driver-sample.cpp.
References ObjectAllocator::Allocate(), OAException::code(), DumpPages(), OAException::E_CORRUPTED_BLOCK, OAConfig::hbBasic, PrintConfig(), PrintCounts(), SHOW_EXCEPTIONS, ValidateCallback(), ObjectAllocator::ValidatePages(), and OAException::what().
void ValidateCallback (const void * block, size_t actual_size)
Definition at line 161 of file driver-sample.cpp.
References SHOWADDRESS2.
Referenced by TestValidate().
Variable Documentation
ObjectAllocator* employeeObjectMgr
Definition at line 38 of file driver-sample.cpp.
Referenced by DoEmployees(), and TestLeak().
int EXTRA_CREDIT = 0
Definition at line 14 of file driver-sample.cpp.
const unsigned objects = 4096
Definition at line 205 of file driver-sample.cpp.
Referenced by Stress(), StressFreeChecking(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), and TestFreeEmptyPages4().
const unsigned pages = 100
Definition at line 206 of file driver-sample.cpp.
Referenced by DumpPages(), DumpPagesEx(), Stress(), StressFreeChecking(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), and TestFreeEmptyPages4().
struct Person PEOPLE[]
Initial value:
 {
  {"Faith", "Ian", 80000, 10},
  {"Tufnel", "Nigel", 90000, 12},
  {"Savage", "Viv", 50000, 4},
  {"Shrimpton", "Mick", 50000, 4},
  {"Besser", "Joe", 40000, 1},
  {"Smalls", "Derek", 80000, 10},
  {"St.Hubbins", "David", 90000, 12},
  {"Fleckman", "Bobbi", 120000, 8},
  {"Eton-Hogg", "Denis", 250000, 22},
  {"Upham", "Denny", 60000, 5},
  {"McLochness", "Ross", 60000, 5},
  {"Pudding", "Ronnie", 50000, 2},
  {"Schindler", "Danny", 60000, 3},
  {"Pettibone", "Jeanine", 85000, 3},
  {"Fame", "Duke", 95000, 8},
  {"Fufkin", "Artie", 45000, 1},
  {"DiBergi", "Marty", 15000, 7},
  {"Floyd", "Pink", 25000, 6},
  {"Zeppelin", "Led", 35000, 3},
  {"Mason", "Nick", 15000, 7},
  {"Wright", "Richard", 17000, 9},
  {"Waters", "Roger", 10000, 3},
  {"Gilmore", "David", 19000, 5}
}
Definition at line 70 of file driver-sample.cpp.
void* ptrs[total]
Definition at line 208 of file driver-sample.cpp.
Referenced by Stress(), StressFreeChecking(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), and TestFreeEmptyPages4().
int SHOW_EXCEPTIONS = 0
Definition at line 13 of file driver-sample.cpp.
Referenced by DisableOA(), DoEmployees(), DoStudents(), Stress(), StressFreeChecking(), TestAlignment(), TestBasicHeaderBlocks(), TestCorruption(), TestExtendedHeaderBlocks(), TestExternalHeaderBlocks(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), TestFreeEmptyPages4(), TestLeak(), and TestValidate().
int SHOWADDRESS1 = 0
Definition at line 10 of file driver-sample.cpp.
Referenced by DumpCallback().
int SHOWADDRESS2 = 0
Definition at line 11 of file driver-sample.cpp.
Referenced by ValidateCallback().
int SHOWREAL = 0
Definition at line 12 of file driver-sample.cpp.
Referenced by DumpPages(), and DumpPagesEx().
ObjectAllocator* studentObjectMgr
Definition at line 37 of file driver-sample.cpp.
Referenced by DisableOA(), and DoStudents().
const unsigned total = objects * pages
Definition at line 207 of file driver-sample.cpp.
Referenced by Stress(), StressFreeChecking(), TestFreeEmptyPages1(), TestFreeEmptyPages2(), TestFreeEmptyPages3(), and TestFreeEmptyPages4().