Sudoku Class Reference
Sudoku Class Reference
#include <Sudoku.h>
Classes
struct SudokuStats
Public Types
enum MessageType {
MSG_STARTING, MSG_FINISHED_OK, MSG_FINISHED_FAIL, MSG_ABORT_CHECK,
MSG_PLACING, MSG_REMOVING, MSG_STARTING, MSG_FINISHED_OK,
MSG_FINISHED_FAIL, MSG_ABORT_CHECK, MSG_PLACING, MSG_REMOVING
}
enum SymbolType { SYM_NUMBER, SYM_LETTER, SYM_NUMBER, SYM_LETTER }
enum MessageType {
MSG_STARTING, MSG_FINISHED_OK, MSG_FINISHED_FAIL, MSG_ABORT_CHECK,
MSG_PLACING, MSG_REMOVING, MSG_STARTING, MSG_FINISHED_OK,
MSG_FINISHED_FAIL, MSG_ABORT_CHECK, MSG_PLACING, MSG_REMOVING
}
enum SymbolType { SYM_NUMBER, SYM_LETTER, SYM_NUMBER, SYM_LETTER }
typedef bool(* SUDOKU_CALLBACK)(const Sudoku &sudoku, const char *board, MessageType message, size_t move, int basesize, int index, char value, int *dup_indexes)
typedef bool(* CALLBACK)(const Sudoku &sudoku, const char *board, MessageType message, size_t move, unsigned basesize, unsigned index, char value, int *dup_indexes)
Public Member Functions
Sudoku (int basesize, SymbolType stype=SYM_NUMBER, SUDOKU_CALLBACK callback=0)
~Sudoku ()
void SetupBoard (const char *values, int size)
void Solve ()
const char * GetBoard () const
SudokuStats GetStats () const
Sudoku (int basesize, SymbolType stype=SYM_NUMBER, CALLBACK callback=0)
~Sudoku ()
void SetupBoard (const char *values, size_t size)
void Solve ()
const char * GetBoard () const
SudokuStats GetStats () const
Static Public Attributes
static const char EMPTY_CHAR = ' '
Private Member Functions
void place_value (unsigned index, char value)
unsigned index_to_row (unsigned index) const
unsigned index_to_col (unsigned index) const
unsigned row_col_to_index (unsigned row, unsigned col) const
bool is_in_conflict (unsigned index) const
int dupe_in_row (unsigned index) const
int dupe_in_col (unsigned index) const
int dupe_in_sqr (unsigned index) const
unsigned find_sqr_start (unsigned index) const
bool is_final_position (unsigned index) const
void update_duplicates (unsigned index)
void insert_into_board (unsigned index, char value)
bool callback (MessageType message, unsigned index, char value)
void place_value (unsigned index, char value)
unsigned index_to_row (unsigned index) const
unsigned index_to_col (unsigned index) const
unsigned row_col_to_index (unsigned row, unsigned col) const
bool is_in_conflict (unsigned index) const
int dupe_in_row (unsigned index) const
int dupe_in_col (unsigned index) const
int dupe_in_sqr (unsigned index) const
unsigned find_sqr_start (unsigned index) const
bool is_final_position (unsigned index) const
void update_duplicates (unsigned index)
void insert_into_board (unsigned index, char value)
bool callback (MessageType message, unsigned index, char value)
Private Attributes
size_t moves_
SymbolType symtype
SudokuStats stats
bool solved
bool backtracking
unsigned boardlength
size_t boardmaxpos
std::string board
char firstelement
char lastelement
int dupes [3]
unsigned blanks [625]
CALLBACK info
Detailed Description
Definition at line 6 of file Sudoku.h.
Member Typedef Documentation
typedef bool(* Sudoku::CALLBACK)(const Sudoku &sudoku,const char *board,MessageType message,size_t move,unsigned basesize,unsigned index,char value,int *dup_indexes)
Definition at line 30 of file Sudokuold.h.
typedef bool(* Sudoku::SUDOKU_CALLBACK)(const Sudoku &sudoku,const char *board,MessageType message,size_t move,int basesize,int index,char value,int *dup_indexes)
Definition at line 27 of file Sudoku.h.
Member Enumeration Documentation
enum Sudoku::MessageType
Enumerator:
MSG_STARTING
MSG_FINISHED_OK
MSG_FINISHED_FAIL
MSG_ABORT_CHECK
MSG_PLACING
MSG_REMOVING
MSG_STARTING
MSG_FINISHED_OK
MSG_FINISHED_FAIL
MSG_ABORT_CHECK
MSG_PLACING
MSG_REMOVING
Definition at line 10 of file Sudoku.h.
enum Sudoku::MessageType
Enumerator:
MSG_STARTING
MSG_FINISHED_OK
MSG_FINISHED_FAIL
MSG_ABORT_CHECK
MSG_PLACING
MSG_REMOVING
MSG_STARTING
MSG_FINISHED_OK
MSG_FINISHED_FAIL
MSG_ABORT_CHECK
MSG_PLACING
MSG_REMOVING
Definition at line 13 of file Sudokuold.h.
enum Sudoku::SymbolType
Enumerator:
SYM_NUMBER
SYM_LETTER
SYM_NUMBER
SYM_LETTER
Definition at line 24 of file Sudokuold.h.
enum Sudoku::SymbolType
Enumerator:
SYM_NUMBER
SYM_LETTER
SYM_NUMBER
SYM_LETTER
Definition at line 21 of file Sudoku.h.
Constructor & Destructor Documentation
Sudoku::Sudoku (int basesize, SymbolType stype = SYM_NUMBER, SUDOKU_CALLBACK callback = 0)
Sudoku::~Sudoku ()
Destructor.
Author:
Louis.coyleii
Date:
10/16/14
Definition at line 74 of file Sudoku.cpp.
Sudoku::Sudoku (int basesize, SymbolType stype = SYM_NUMBER, CALLBACK callback = 0)
Constructor.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
basesize Size of each square for the board.
stype Type of the symbol for the board (letters or numbers).
callback Whether to callback with constructor information.
Definition at line 39 of file Sudoku.cpp.
References Sudoku::SudokuStats::basesize, boardlength, callback(), dupes, firstelement, info, lastelement, stats, and SYM_NUMBER.
Sudoku::~Sudoku ()
Member Function Documentation
bool Sudoku::callback (MessageType message, unsigned index, char value) [private]
Calls the callback function for the index and value with the message.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
message The message to send with the callback.
index Position of the cell.
value Symbol (value) for the cell.
Returns:
bool
Definition at line 442 of file Sudoku.cpp.
References Sudoku::SudokuStats::basesize, board, dupes, info, Sudoku::SudokuStats::moves, stats, and update_duplicates().
Referenced by place_value(), Solve(), and Sudoku().
bool Sudoku::callback (MessageType message, unsigned index, char value) [private]
int Sudoku::dupe_in_col (unsigned index) const [private]
Returns whether or not the value at index is dupe in the column.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
Returns:
bool Whether or not the value at index is dupe in the column.
Definition at line 321 of file Sudoku.cpp.
References board, boardlength, index_to_col(), and row_col_to_index().
Referenced by is_in_conflict(), and update_duplicates().
int Sudoku::dupe_in_col (unsigned index) const [private]
int Sudoku::dupe_in_row (unsigned index) const [private]
Returns whether or not the value at index is dupe in the row.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
Returns:
bool Whether or not the value at index is dupe in the row.
Definition at line 295 of file Sudoku.cpp.
References board, boardlength, index_to_row(), and row_col_to_index().
Referenced by is_in_conflict(), and update_duplicates().
int Sudoku::dupe_in_row (unsigned index) const [private]
int Sudoku::dupe_in_sqr (unsigned index) const [private]
Returns whether or not the value at index is dupe in the square.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
Returns:
bool Whether or not the value at index is dupe in the square.
Definition at line 347 of file Sudoku.cpp.
References Sudoku::SudokuStats::basesize, board, boardlength, find_sqr_start(), and stats.
Referenced by is_in_conflict(), and update_duplicates().
int Sudoku::dupe_in_sqr (unsigned index) const [private]
unsigned Sudoku::find_sqr_start (unsigned index) const [private]
Returns the start of the square that the passed index is in.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
Returns:
bool The index of the start of the square that index is in.
Definition at line 379 of file Sudoku.cpp.
References Sudoku::SudokuStats::basesize, index_to_col(), index_to_row(), row_col_to_index(), and stats.
Referenced by dupe_in_sqr().
unsigned Sudoku::find_sqr_start (unsigned index) const [private]
const char * Sudoku::GetBoard () const
Gets the board, for debugging with the driver.
Author:
Louis.coyleii
Date:
10/16/14
Returns:
char* The current board.
Definition at line 462 of file Sudoku.cpp.
References board.
const char* Sudoku::GetBoard () const
SudokuStats Sudoku::GetStats () const
Sudoku::SudokuStats Sudoku::GetStats () const
Returns the current stats for the board.
Author:
Louis.coyleii
Date:
10/16/14
Returns:
SodokuStats The current stats for the board.
Definition at line 477 of file Sudoku.cpp.
References stats.
Referenced by PrintStats().
unsigned Sudoku::index_to_col (unsigned index) const [private]
unsigned Sudoku::index_to_col (unsigned index) const [private]
Returns the column of the index.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
Returns:
unsigned The index of the column.
Definition at line 233 of file Sudoku.cpp.
References boardlength.
Referenced by dupe_in_col(), and find_sqr_start().
unsigned Sudoku::index_to_row (unsigned index) const [private]
unsigned Sudoku::index_to_row (unsigned index) const [private]
Returns the row of the index.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
Returns:
unsigned The index of the row.
Definition at line 215 of file Sudoku.cpp.
References boardlength.
Referenced by dupe_in_row(), and find_sqr_start().
void Sudoku::insert_into_board (unsigned index, char value) [private]
void Sudoku::insert_into_board (unsigned index, char value) [private]
Inserts the value at the index.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
value Symbol (value) for the cell.
Definition at line 136 of file Sudoku.cpp.
References board, Sudoku::SudokuStats::moves, Sudoku::SudokuStats::placed, and stats.
Referenced by place_value().
bool Sudoku::is_final_position (unsigned index) const [private]
bool Sudoku::is_final_position (unsigned index) const [private]
Returns whether or not the value at index is the final position.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
Returns:
bool Whether or not the index is the last position on the board.
Definition at line 403 of file Sudoku.cpp.
References boardmaxpos.
Referenced by place_value().
bool Sudoku::is_in_conflict (unsigned index) const [private]
Returns whether or not the value at index is allowable.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
Returns:
bool Whether or not the value at index is allowable.
Definition at line 270 of file Sudoku.cpp.
References dupe_in_col(), dupe_in_row(), and dupe_in_sqr().
Referenced by place_value().
bool Sudoku::is_in_conflict (unsigned index) const [private]
void Sudoku::place_value (unsigned index, char value) [private]
Recursively attemps to place the value at the index.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
value Symbol (value) for the cell.
Definition at line 155 of file Sudoku.cpp.
References Sudoku::SudokuStats::backtracks, board, callback(), firstelement, insert_into_board(), is_final_position(), is_in_conflict(), lastelement, MSG_ABORT_CHECK, MSG_FINISHED_OK, MSG_PLACING, MSG_REMOVING, Sudoku::SudokuStats::placed, and stats.
Referenced by Solve().
void Sudoku::place_value (unsigned index, char value) [private]
unsigned Sudoku::row_col_to_index (unsigned row, unsigned col) const [private]
Returns the index of the row or column.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
row The row number to convert.
col The col number to convert.
Returns:
unsigned The index of the (row,col).
Definition at line 252 of file Sudoku.cpp.
References boardlength.
Referenced by dupe_in_col(), dupe_in_row(), and find_sqr_start().
unsigned Sudoku::row_col_to_index (unsigned row, unsigned col) const [private]
void Sudoku::SetupBoard (const char * values, size_t size)
Sets up the board with the passed in values.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
values Symbols (values) for the board.
size Size of the board to set up.
Definition at line 90 of file Sudoku.cpp.
References board, and boardmaxpos.
void Sudoku::SetupBoard (const char * values, int size)
Referenced by RunTest().
void Sudoku::Solve ()
Starts the search for the solution to the board.
Author:
Louis.coyleii
Date:
10/16/14
Definition at line 113 of file Sudoku.cpp.
References callback(), firstelement, MSG_ABORT_CHECK, MSG_STARTING, and place_value().
Referenced by RunTest().
void Sudoku::Solve ()
void Sudoku::update_duplicates (unsigned index) [private]
Adds the index to the list of duplicates.
Author:
Louis.coyleii
Date:
10/16/14
Parameters:
index Position of the cell.
Definition at line 419 of file Sudoku.cpp.
References dupe_in_col(), dupe_in_row(), dupe_in_sqr(), and dupes.
Referenced by callback().
void Sudoku::update_duplicates (unsigned index) [private]
Member Data Documentation
bool Sudoku::backtracking [private]
Definition at line 69 of file Sudoku.h.
unsigned Sudoku::blanks [private]
Definition at line 76 of file Sudoku.h.
std::string Sudoku::board [private]
Definition at line 72 of file Sudoku.h.
Referenced by callback(), dupe_in_col(), dupe_in_row(), dupe_in_sqr(), GetBoard(), insert_into_board(), place_value(), and SetupBoard().
unsigned Sudoku::boardlength [private]
Definition at line 70 of file Sudoku.h.
Referenced by dupe_in_col(), dupe_in_row(), dupe_in_sqr(), index_to_col(), index_to_row(), row_col_to_index(), and Sudoku().
size_t Sudoku::boardmaxpos [private]
Definition at line 71 of file Sudoku.h.
Referenced by is_final_position(), and SetupBoard().
int Sudoku::dupes [private]
Definition at line 75 of file Sudoku.h.
Referenced by callback(), Sudoku(), and update_duplicates().
static const char Sudoku::EMPTY_CHAR = ' ' [static]
Definition at line 23 of file Sudoku.h.
char Sudoku::firstelement [private]
Definition at line 73 of file Sudoku.h.
Referenced by place_value(), Solve(), and Sudoku().
CALLBACK Sudoku::info [private]
Definition at line 77 of file Sudoku.h.
Referenced by callback(), and Sudoku().
char Sudoku::lastelement [private]
Definition at line 74 of file Sudoku.h.
Referenced by place_value(), and Sudoku().
size_t Sudoku::moves_ [private]
Definition at line 65 of file Sudoku.h.
bool Sudoku::solved [private]
Definition at line 68 of file Sudoku.h.
SudokuStats Sudoku::stats [private]
Definition at line 67 of file Sudoku.h.
Referenced by callback(), dupe_in_sqr(), find_sqr_start(), GetStats(), insert_into_board(), place_value(), and Sudoku().
SymbolType Sudoku::symtype [private]
Definition at line 66 of file Sudoku.h.
The documentation for this class was generated from the following files:
Sudoku.h
Sudokuold.h
Sudoku.cpp